//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("_CloneRoutingRuleSet")]
	public partial class _CloneRoutingRuleSetResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string RoutingRuleSetCopyRecordId = "RoutingRuleSetCopyRecordId";
		}
		
		public const string ActionLogicalName = "_CloneRoutingRuleSet";
		
		public _CloneRoutingRuleSetResponse()
		{
		}
		
		public string RoutingRuleSetCopyRecordId
		{
			get
			{
				if (this.Results.Contains("RoutingRuleSetCopyRecordId"))
				{
					return ((string)(this.Results["RoutingRuleSetCopyRecordId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["RoutingRuleSetCopyRecordId"] = value;
			}
		}
	}
}