//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("_CloneRoutingRuleSet")]
	public partial class _CloneRoutingRuleSetRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string RoutingRuleSetIdToClone = "RoutingRuleSetIdToClone";
			public const string RoutingRuleSetIdToOverwrite = "RoutingRuleSetIdToOverwrite";
			public const string Options = "Options";
		}
		
		public const string ActionLogicalName = "_CloneRoutingRuleSet";
		
		public Microsoft.Xrm.Sdk.EntityReference RoutingRuleSetIdToClone
		{
			get
			{
				if (this.Parameters.Contains("RoutingRuleSetIdToClone"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["RoutingRuleSetIdToClone"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["RoutingRuleSetIdToClone"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference RoutingRuleSetIdToOverwrite
		{
			get
			{
				if (this.Parameters.Contains("RoutingRuleSetIdToOverwrite"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["RoutingRuleSetIdToOverwrite"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["RoutingRuleSetIdToOverwrite"] = value;
			}
		}
		
		public string Options
		{
			get
			{
				if (this.Parameters.Contains("Options"))
				{
					return ((string)(this.Parameters["Options"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Options"] = value;
			}
		}
		
		public _CloneRoutingRuleSetRequest()
		{
			this.RequestName = "_CloneRoutingRuleSet";
			this.RoutingRuleSetIdToClone = default(Microsoft.Xrm.Sdk.EntityReference);
			this.Options = default(string);
		}
	}
}