//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("_EvaluateRuleAndRoute")]
	public partial class _EvaluateRuleAndRouteRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Target = "Target";
			public const string RoutingRuleSetId = "RoutingRuleSetId";
		}
		
		public const string ActionLogicalName = "_EvaluateRuleAndRoute";
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public string RoutingRuleSetId
		{
			get
			{
				if (this.Parameters.Contains("RoutingRuleSetId"))
				{
					return ((string)(this.Parameters["RoutingRuleSetId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RoutingRuleSetId"] = value;
			}
		}
		
		public _EvaluateRuleAndRouteRequest()
		{
			this.RequestName = "_EvaluateRuleAndRoute";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
			this.RoutingRuleSetId = default(string);
		}
	}
}