//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("_EvaluateSearchRequest")]
	public partial class _EvaluateSearchRequestRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string ServiceAppointmentId = "ServiceAppointmentId";
			public const string ServiceId = "ServiceId";
			public const string DateOptionSet = "DateOptionSet";
			public const string TimeOptionSet = "TimeOptionSet";
			public const string DayList = "DayList";
			public const string RequiredResources = "RequiredResources";
			public const string SearchWindowStart = "SearchWindowStart";
			public const string SearchWindowEnd = "SearchWindowEnd";
			public const string SearchRecurrenceStart = "SearchRecurrenceStart";
			public const string TimeRangeEnd = "TimeRangeEnd";
			public const string Duration = "Duration";
			public const string Direction = "Direction";
			public const string Sites = "Sites";
		}
		
		public const string ActionLogicalName = "_EvaluateSearchRequest";
		
		public string ServiceAppointmentId
		{
			get
			{
				if (this.Parameters.Contains("ServiceAppointmentId"))
				{
					return ((string)(this.Parameters["ServiceAppointmentId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ServiceAppointmentId"] = value;
			}
		}
		
		public string ServiceId
		{
			get
			{
				if (this.Parameters.Contains("ServiceId"))
				{
					return ((string)(this.Parameters["ServiceId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ServiceId"] = value;
			}
		}
		
		public int DateOptionSet
		{
			get
			{
				if (this.Parameters.Contains("DateOptionSet"))
				{
					return ((int)(this.Parameters["DateOptionSet"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["DateOptionSet"] = value;
			}
		}
		
		public int TimeOptionSet
		{
			get
			{
				if (this.Parameters.Contains("TimeOptionSet"))
				{
					return ((int)(this.Parameters["TimeOptionSet"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["TimeOptionSet"] = value;
			}
		}
		
		public string DayList
		{
			get
			{
				if (this.Parameters.Contains("DayList"))
				{
					return ((string)(this.Parameters["DayList"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["DayList"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection RequiredResources
		{
			get
			{
				if (this.Parameters.Contains("RequiredResources"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Parameters["RequiredResources"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Parameters["RequiredResources"] = value;
			}
		}
		
		public string SearchWindowStart
		{
			get
			{
				if (this.Parameters.Contains("SearchWindowStart"))
				{
					return ((string)(this.Parameters["SearchWindowStart"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SearchWindowStart"] = value;
			}
		}
		
		public string SearchWindowEnd
		{
			get
			{
				if (this.Parameters.Contains("SearchWindowEnd"))
				{
					return ((string)(this.Parameters["SearchWindowEnd"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SearchWindowEnd"] = value;
			}
		}
		
		public int SearchRecurrenceStart
		{
			get
			{
				if (this.Parameters.Contains("SearchRecurrenceStart"))
				{
					return ((int)(this.Parameters["SearchRecurrenceStart"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["SearchRecurrenceStart"] = value;
			}
		}
		
		public int TimeRangeEnd
		{
			get
			{
				if (this.Parameters.Contains("TimeRangeEnd"))
				{
					return ((int)(this.Parameters["TimeRangeEnd"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["TimeRangeEnd"] = value;
			}
		}
		
		public int Duration
		{
			get
			{
				if (this.Parameters.Contains("Duration"))
				{
					return ((int)(this.Parameters["Duration"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["Duration"] = value;
			}
		}
		
		public int Direction
		{
			get
			{
				if (this.Parameters.Contains("Direction"))
				{
					return ((int)(this.Parameters["Direction"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["Direction"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection Sites
		{
			get
			{
				if (this.Parameters.Contains("Sites"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Parameters["Sites"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Parameters["Sites"] = value;
			}
		}
		
		public _EvaluateSearchRequestRequest()
		{
			this.RequestName = "_EvaluateSearchRequest";
			this.ServiceId = default(string);
			this.Duration = default(int);
		}
	}
}