//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("_GetServiceTreeData")]
	public partial class _GetServiceTreeDataResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string TreeObject = "TreeObject";
		}
		
		public const string ActionLogicalName = "_GetServiceTreeData";
		
		public _GetServiceTreeDataResponse()
		{
		}
		
		public string TreeObject
		{
			get
			{
				if (this.Results.Contains("TreeObject"))
				{
					return ((string)(this.Results["TreeObject"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["TreeObject"] = value;
			}
		}
	}
}