//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("_GetServiceTreeData")]
	public partial class _GetServiceTreeDataRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string ServiceId = "ServiceId";
			public const string InputSource = "InputSource";
		}
		
		public const string ActionLogicalName = "_GetServiceTreeData";
		
		public string ServiceId
		{
			get
			{
				if (this.Parameters.Contains("ServiceId"))
				{
					return ((string)(this.Parameters["ServiceId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ServiceId"] = value;
			}
		}
		
		public string InputSource
		{
			get
			{
				if (this.Parameters.Contains("InputSource"))
				{
					return ((string)(this.Parameters["InputSource"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["InputSource"] = value;
			}
		}
		
		public _GetServiceTreeDataRequest()
		{
			this.RequestName = "_GetServiceTreeData";
			this.ServiceId = default(string);
		}
	}
}