//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("_ResourcesRemoveUpdateAction")]
	public partial class _ResourcesRemoveUpdateActionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string ResourcesToBeRemoved = "ResourcesToBeRemoved";
			public const string ResourceGroupId = "ResourceGroupId";
		}
		
		public const string ActionLogicalName = "_ResourcesRemoveUpdateAction";
		
		public string ResourcesToBeRemoved
		{
			get
			{
				if (this.Parameters.Contains("ResourcesToBeRemoved"))
				{
					return ((string)(this.Parameters["ResourcesToBeRemoved"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ResourcesToBeRemoved"] = value;
			}
		}
		
		public string ResourceGroupId
		{
			get
			{
				if (this.Parameters.Contains("ResourceGroupId"))
				{
					return ((string)(this.Parameters["ResourceGroupId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ResourceGroupId"] = value;
			}
		}
		
		public _ResourcesRemoveUpdateActionRequest()
		{
			this.RequestName = "_ResourcesRemoveUpdateAction";
		}
	}
}