//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("_ResourcesAddUpdateAction")]
	public partial class _ResourcesAddUpdateActionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string NewlyAddedResources = "NewlyAddedResources";
			public const string ResourceGroupId = "ResourceGroupId";
			public const string ResourceGroupsToAdd = "ResourceGroupsToAdd";
		}
		
		public const string ActionLogicalName = "_ResourcesAddUpdateAction";
		
		public string NewlyAddedResources
		{
			get
			{
				if (this.Parameters.Contains("NewlyAddedResources"))
				{
					return ((string)(this.Parameters["NewlyAddedResources"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["NewlyAddedResources"] = value;
			}
		}
		
		public string ResourceGroupId
		{
			get
			{
				if (this.Parameters.Contains("ResourceGroupId"))
				{
					return ((string)(this.Parameters["ResourceGroupId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ResourceGroupId"] = value;
			}
		}
		
		public string ResourceGroupsToAdd
		{
			get
			{
				if (this.Parameters.Contains("ResourceGroupsToAdd"))
				{
					return ((string)(this.Parameters["ResourceGroupsToAdd"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ResourceGroupsToAdd"] = value;
			}
		}
		
		public _ResourcesAddUpdateActionRequest()
		{
			this.RequestName = "_ResourcesAddUpdateAction";
		}
	}
}