//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("_RetrieveActivitiesByResources")]
	public partial class _RetrieveActivitiesByResourcesResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string ExceptionMessage = "ExceptionMessage";
			public const string Result = "Result";
		}
		
		public const string ActionLogicalName = "_RetrieveActivitiesByResources";
		
		public _RetrieveActivitiesByResourcesResponse()
		{
		}
		
		public string ExceptionMessage
		{
			get
			{
				if (this.Results.Contains("ExceptionMessage"))
				{
					return ((string)(this.Results["ExceptionMessage"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["ExceptionMessage"] = value;
			}
		}
		
		public string Result
		{
			get
			{
				if (this.Results.Contains("Result"))
				{
					return ((string)(this.Results["Result"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Result"] = value;
			}
		}
	}
}