//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("_RetrieveActivitiesByResources")]
	public partial class _RetrieveActivitiesByResourcesRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string StartDate = "StartDate";
			public const string EndDate = "EndDate";
			public const string ResourceIds = "ResourceIds";
			public const string ActivityType = "ActivityType";
		}
		
		public const string ActionLogicalName = "_RetrieveActivitiesByResources";
		
		public System.DateTime StartDate
		{
			get
			{
				if (this.Parameters.Contains("StartDate"))
				{
					return ((System.DateTime)(this.Parameters["StartDate"]));
				}
				else
				{
					return default(System.DateTime);
				}
			}
			set
			{
				this.Parameters["StartDate"] = value;
			}
		}
		
		public System.DateTime EndDate
		{
			get
			{
				if (this.Parameters.Contains("EndDate"))
				{
					return ((System.DateTime)(this.Parameters["EndDate"]));
				}
				else
				{
					return default(System.DateTime);
				}
			}
			set
			{
				this.Parameters["EndDate"] = value;
			}
		}
		
		public string ResourceIds
		{
			get
			{
				if (this.Parameters.Contains("ResourceIds"))
				{
					return ((string)(this.Parameters["ResourceIds"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ResourceIds"] = value;
			}
		}
		
		public int ActivityType
		{
			get
			{
				if (this.Parameters.Contains("ActivityType"))
				{
					return ((int)(this.Parameters["ActivityType"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["ActivityType"] = value;
			}
		}
		
		public _RetrieveActivitiesByResourcesRequest()
		{
			this.RequestName = "_RetrieveActivitiesByResources";
			this.StartDate = default(System.DateTime);
			this.EndDate = default(System.DateTime);
			this.ResourceIds = default(string);
			this.ActivityType = default(int);
		}
	}
}