//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("_RoutingRuleSetValidation")]
	public partial class _RoutingRuleSetValidationRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string RoutingRuleSet = "RoutingRuleSet";
		}
		
		public const string ActionLogicalName = "_RoutingRuleSetValidation";
		
		public Microsoft.Xrm.Sdk.EntityReference RoutingRuleSet
		{
			get
			{
				if (this.Parameters.Contains("RoutingRuleSet"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["RoutingRuleSet"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["RoutingRuleSet"] = value;
			}
		}
		
		public _RoutingRuleSetValidationRequest()
		{
			this.RequestName = "_RoutingRuleSetValidation";
			this.RoutingRuleSet = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
}