//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("_SaveServiceTreeData")]
	public partial class _SaveServiceTreeDataRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string RootNodeId = "RootNodeId";
			public const string ResourceRuleList = "ResourceRuleList";
		}
		
		public const string ActionLogicalName = "_SaveServiceTreeData";
		
		public string RootNodeId
		{
			get
			{
				if (this.Parameters.Contains("RootNodeId"))
				{
					return ((string)(this.Parameters["RootNodeId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RootNodeId"] = value;
			}
		}
		
		public string ResourceRuleList
		{
			get
			{
				if (this.Parameters.Contains("ResourceRuleList"))
				{
					return ((string)(this.Parameters["ResourceRuleList"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ResourceRuleList"] = value;
			}
		}
		
		public _SaveServiceTreeDataRequest()
		{
			this.RequestName = "_SaveServiceTreeData";
			this.RootNodeId = default(string);
		}
	}
}