//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("AlmHandler")]
	public partial class AlmHandlerResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string result = "result";
		}
		
		public const string ActionLogicalName = "AlmHandler";
		
		public AlmHandlerResponse()
		{
		}
		
		public string result
		{
			get
			{
				if (this.Results.Contains("result"))
				{
					return ((string)(this.Results["result"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["result"] = value;
			}
		}
	}
}