//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("AnalyzeSentiment")]
	public partial class AnalyzeSentimentResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string documentScores = "documentScores";
			public const string sentences = "sentences";
			public const string sentiment = "sentiment";
		}
		
		public const string ActionLogicalName = "AnalyzeSentiment";
		
		public AnalyzeSentimentResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.Entity documentScores
		{
			get
			{
				if (this.Results.Contains("documentScores"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Results["documentScores"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
			set
			{
				this.Results["documentScores"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection sentences
		{
			get
			{
				if (this.Results.Contains("sentences"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Results["sentences"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Results["sentences"] = value;
			}
		}
		
		public string sentiment
		{
			get
			{
				if (this.Results.Contains("sentiment"))
				{
					return ((string)(this.Results["sentiment"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["sentiment"] = value;
			}
		}
	}
}