//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/8.1/Contracts")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("CreatePolymorphicLookupAttribute")]
	public partial class CreatePolymorphicLookupAttributeResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string AttributeId = "AttributeId";
			public const string RelationshipIds = "RelationshipIds";
		}
		
		public const string ActionLogicalName = "CreatePolymorphicLookupAttribute";
		
		public CreatePolymorphicLookupAttributeResponse()
		{
		}
		
		public System.Guid AttributeId
		{
			get
			{
				if (this.Results.Contains("AttributeId"))
				{
					return ((System.Guid)(this.Results["AttributeId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Results["AttributeId"] = value;
			}
		}
		
		public System.Guid[] RelationshipIds
		{
			get
			{
				if (this.Results.Contains("RelationshipIds"))
				{
					return ((System.Guid[])(this.Results["RelationshipIds"]));
				}
				else
				{
					return default(System.Guid[]);
				}
			}
			set
			{
				this.Results["RelationshipIds"] = value;
			}
		}
	}
}