//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("DetectLanguage")]
	public partial class DetectLanguageResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string language = "language";
			public const string score = "score";
		}
		
		public const string ActionLogicalName = "DetectLanguage";
		
		public DetectLanguageResponse()
		{
		}
		
		public string language
		{
			get
			{
				if (this.Results.Contains("language"))
				{
					return ((string)(this.Results["language"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["language"] = value;
			}
		}
		
		public decimal score
		{
			get
			{
				if (this.Results.Contains("score"))
				{
					return ((decimal)(this.Results["score"]));
				}
				else
				{
					return default(decimal);
				}
			}
			set
			{
				this.Results["score"] = value;
			}
		}
	}
}