//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("DownloadSolutionExportData")]
	public partial class DownloadSolutionExportDataResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string ExportSolutionFile = "ExportSolutionFile";
		}
		
		public const string ActionLogicalName = "DownloadSolutionExportData";
		
		public DownloadSolutionExportDataResponse()
		{
		}
		
		public byte[] ExportSolutionFile
		{
			get
			{
				if (this.Results.Contains("ExportSolutionFile"))
				{
					return ((byte[])(this.Results["ExportSolutionFile"]));
				}
				else
				{
					return default(byte[]);
				}
			}
			set
			{
				this.Results["ExportSolutionFile"] = value;
			}
		}
	}
}