//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("ExportSolutionAsync")]
	public partial class ExportSolutionAsyncRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string ExportGeneralSettings = "ExportGeneralSettings";
			public const string ExportAutoNumberingSettings = "ExportAutoNumberingSettings";
			public const string ExportCalendarSettings = "ExportCalendarSettings";
			public const string ExportSales = "ExportSales";
			public const string ExportRelationshipRoles = "ExportRelationshipRoles";
			public const string ExportEmailTrackingSettings = "ExportEmailTrackingSettings";
			public const string ExportCustomizationSettings = "ExportCustomizationSettings";
			public const string TargetVersion = "TargetVersion";
			public const string ExportIsvConfig = "ExportIsvConfig";
			public const string SolutionName = "SolutionName";
			public const string ExportOutlookSynchronizationSettings = "ExportOutlookSynchronizationSettings";
			public const string Managed = "Managed";
			public const string ExportMarketingSettings = "ExportMarketingSettings";
			public const string ExportExternalApplications = "ExportExternalApplications";
			public const string ExportComponentsParams = "ExportComponentsParams";
		}
		
		public const string ActionLogicalName = "ExportSolutionAsync";
		
		public bool ExportGeneralSettings
		{
			get
			{
				if (this.Parameters.Contains("ExportGeneralSettings"))
				{
					return ((bool)(this.Parameters["ExportGeneralSettings"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["ExportGeneralSettings"] = value;
			}
		}
		
		public bool ExportAutoNumberingSettings
		{
			get
			{
				if (this.Parameters.Contains("ExportAutoNumberingSettings"))
				{
					return ((bool)(this.Parameters["ExportAutoNumberingSettings"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["ExportAutoNumberingSettings"] = value;
			}
		}
		
		public bool ExportCalendarSettings
		{
			get
			{
				if (this.Parameters.Contains("ExportCalendarSettings"))
				{
					return ((bool)(this.Parameters["ExportCalendarSettings"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["ExportCalendarSettings"] = value;
			}
		}
		
		public bool ExportSales
		{
			get
			{
				if (this.Parameters.Contains("ExportSales"))
				{
					return ((bool)(this.Parameters["ExportSales"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["ExportSales"] = value;
			}
		}
		
		public bool ExportRelationshipRoles
		{
			get
			{
				if (this.Parameters.Contains("ExportRelationshipRoles"))
				{
					return ((bool)(this.Parameters["ExportRelationshipRoles"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["ExportRelationshipRoles"] = value;
			}
		}
		
		public bool ExportEmailTrackingSettings
		{
			get
			{
				if (this.Parameters.Contains("ExportEmailTrackingSettings"))
				{
					return ((bool)(this.Parameters["ExportEmailTrackingSettings"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["ExportEmailTrackingSettings"] = value;
			}
		}
		
		public bool ExportCustomizationSettings
		{
			get
			{
				if (this.Parameters.Contains("ExportCustomizationSettings"))
				{
					return ((bool)(this.Parameters["ExportCustomizationSettings"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["ExportCustomizationSettings"] = value;
			}
		}
		
		public string TargetVersion
		{
			get
			{
				if (this.Parameters.Contains("TargetVersion"))
				{
					return ((string)(this.Parameters["TargetVersion"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["TargetVersion"] = value;
			}
		}
		
		public bool ExportIsvConfig
		{
			get
			{
				if (this.Parameters.Contains("ExportIsvConfig"))
				{
					return ((bool)(this.Parameters["ExportIsvConfig"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["ExportIsvConfig"] = value;
			}
		}
		
		public string SolutionName
		{
			get
			{
				if (this.Parameters.Contains("SolutionName"))
				{
					return ((string)(this.Parameters["SolutionName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SolutionName"] = value;
			}
		}
		
		public bool ExportOutlookSynchronizationSettings
		{
			get
			{
				if (this.Parameters.Contains("ExportOutlookSynchronizationSettings"))
				{
					return ((bool)(this.Parameters["ExportOutlookSynchronizationSettings"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["ExportOutlookSynchronizationSettings"] = value;
			}
		}
		
		public bool Managed
		{
			get
			{
				if (this.Parameters.Contains("Managed"))
				{
					return ((bool)(this.Parameters["Managed"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["Managed"] = value;
			}
		}
		
		public bool ExportMarketingSettings
		{
			get
			{
				if (this.Parameters.Contains("ExportMarketingSettings"))
				{
					return ((bool)(this.Parameters["ExportMarketingSettings"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["ExportMarketingSettings"] = value;
			}
		}
		
		public bool ExportExternalApplications
		{
			get
			{
				if (this.Parameters.Contains("ExportExternalApplications"))
				{
					return ((bool)(this.Parameters["ExportExternalApplications"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["ExportExternalApplications"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.ExportComponentsParams ExportComponentsParams
		{
			get
			{
				if (this.Parameters.Contains("ExportComponentsParams"))
				{
					return ((Microsoft.Xrm.Sdk.ExportComponentsParams)(this.Parameters["ExportComponentsParams"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.ExportComponentsParams);
				}
			}
			set
			{
				this.Parameters["ExportComponentsParams"] = value;
			}
		}
		
		public ExportSolutionAsyncRequest()
		{
			this.RequestName = "ExportSolutionAsync";
			this.SolutionName = default(string);
			this.Managed = default(bool);
		}
	}
}