//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("ExtractTextEntities")]
	public partial class ExtractTextEntitiesResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string entities = "entities";
			public const string originalText = "originalText";
			public const string textScore = "textScore";
		}
		
		public const string ActionLogicalName = "ExtractTextEntities";
		
		public ExtractTextEntitiesResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection entities
		{
			get
			{
				if (this.Results.Contains("entities"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Results["entities"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Results["entities"] = value;
			}
		}
		
		public string originalText
		{
			get
			{
				if (this.Results.Contains("originalText"))
				{
					return ((string)(this.Results["originalText"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["originalText"] = value;
			}
		}
		
		public decimal textScore
		{
			get
			{
				if (this.Results.Contains("textScore"))
				{
					return ((decimal)(this.Results["textScore"]));
				}
				else
				{
					return default(decimal);
				}
			}
			set
			{
				this.Results["textScore"] = value;
			}
		}
	}
}