//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("GetJobStatus")]
	public partial class GetJobStatusRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string istrain = "istrain";
			public const string correlationid = "correlationid";
			public const string aimodelid = "aimodelid";
		}
		
		public const string ActionLogicalName = "GetJobStatus";
		
		public bool istrain
		{
			get
			{
				if (this.Parameters.Contains("istrain"))
				{
					return ((bool)(this.Parameters["istrain"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["istrain"] = value;
			}
		}
		
		public string correlationid
		{
			get
			{
				if (this.Parameters.Contains("correlationid"))
				{
					return ((string)(this.Parameters["correlationid"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["correlationid"] = value;
			}
		}
		
		public string aimodelid
		{
			get
			{
				if (this.Parameters.Contains("aimodelid"))
				{
					return ((string)(this.Parameters["aimodelid"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["aimodelid"] = value;
			}
		}
		
		public GetJobStatusRequest()
		{
			this.RequestName = "GetJobStatus";
			this.istrain = default(bool);
		}
	}
}