//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("install")]
	public partial class installResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string connectionId = "connectionId";
			public const string flowTriggerUri = "flowTriggerUri";
		}
		
		public const string ActionLogicalName = "install";
		
		public installResponse()
		{
		}
		
		public string connectionId
		{
			get
			{
				if (this.Results.Contains("connectionId"))
				{
					return ((string)(this.Results["connectionId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["connectionId"] = value;
			}
		}
		
		public string flowTriggerUri
		{
			get
			{
				if (this.Results.Contains("flowTriggerUri"))
				{
					return ((string)(this.Results["flowTriggerUri"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["flowTriggerUri"] = value;
			}
		}
	}
}