//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("install")]
	public partial class installRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Target = "Target";
			public const string connectionReferences = "connectionReferences";
		}
		
		public const string ActionLogicalName = "install";
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public string connectionReferences
		{
			get
			{
				if (this.Parameters.Contains("connectionReferences"))
				{
					return ((string)(this.Parameters["connectionReferences"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["connectionReferences"] = value;
			}
		}
		
		public installRequest()
		{
			this.RequestName = "install";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
			this.connectionReferences = default(string);
		}
	}
}