//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetSILicenseStatus")]
	public partial class msdyn_GetSILicenseStatusResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string SILicenseStatus = "SILicenseStatus";
		}
		
		public const string ActionLogicalName = "msdyn_GetSILicenseStatus";
		
		public msdyn_GetSILicenseStatusResponse()
		{
		}
		
		public string SILicenseStatus
		{
			get
			{
				if (this.Results.Contains("SILicenseStatus"))
				{
					return ((string)(this.Results["SILicenseStatus"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["SILicenseStatus"] = value;
			}
		}
	}
}