//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_MarketingMetadataUpdate")]
	public partial class msdyn_MarketingMetadataUpdateResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string resultCode = "resultCode";
		}
		
		public const string ActionLogicalName = "msdyn_MarketingMetadataUpdate";
		
		public msdyn_MarketingMetadataUpdateResponse()
		{
		}
		
		public int resultCode
		{
			get
			{
				if (this.Results.Contains("resultCode"))
				{
					return ((int)(this.Results["resultCode"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Results["resultCode"] = value;
			}
		}
	}
}