//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_DataValidationApi")]
	public partial class msdyn_DataValidationApiRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string ApiType = "ApiType";
			public const string ApiPayLoad = "ApiPayLoad";
		}
		
		public const string ActionLogicalName = "msdyn_DataValidationApi";
		
		public int ApiType
		{
			get
			{
				if (this.Parameters.Contains("ApiType"))
				{
					return ((int)(this.Parameters["ApiType"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["ApiType"] = value;
			}
		}
		
		public string ApiPayLoad
		{
			get
			{
				if (this.Parameters.Contains("ApiPayLoad"))
				{
					return ((string)(this.Parameters["ApiPayLoad"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ApiPayLoad"] = value;
			}
		}
		
		public msdyn_DataValidationApiRequest()
		{
			this.RequestName = "msdyn_DataValidationApi";
			this.ApiType = default(int);
		}
	}
}