//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_MigrateArcProactiveRun")]
	public partial class msdyn_MigrateArcProactiveRunResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string Exception = "Exception";
			public const string OutputString = "OutputString";
		}
		
		public const string ActionLogicalName = "msdyn_MigrateArcProactiveRun";
		
		public msdyn_MigrateArcProactiveRunResponse()
		{
		}
		
		public string Exception
		{
			get
			{
				if (this.Results.Contains("Exception"))
				{
					return ((string)(this.Results["Exception"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Exception"] = value;
			}
		}
		
		public string OutputString
		{
			get
			{
				if (this.Results.Contains("OutputString"))
				{
					return ((string)(this.Results["OutputString"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["OutputString"] = value;
			}
		}
	}
}