//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetTimeLineRecords")]
	public partial class msdyn_GetTimeLineRecordsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string RegardingObjectId = "RegardingObjectId";
			public const string NumberOfRecords = "NumberOfRecords";
		}
		
		public const string ActionLogicalName = "msdyn_GetTimeLineRecords";
		
		public string RegardingObjectId
		{
			get
			{
				if (this.Parameters.Contains("RegardingObjectId"))
				{
					return ((string)(this.Parameters["RegardingObjectId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RegardingObjectId"] = value;
			}
		}
		
		public string NumberOfRecords
		{
			get
			{
				if (this.Parameters.Contains("NumberOfRecords"))
				{
					return ((string)(this.Parameters["NumberOfRecords"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["NumberOfRecords"] = value;
			}
		}
		
		public msdyn_GetTimeLineRecordsRequest()
		{
			this.RequestName = "msdyn_GetTimeLineRecords";
			this.RegardingObjectId = default(string);
			this.NumberOfRecords = default(string);
		}
	}
}