//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_MigrateArc")]
	public partial class msdyn_MigrateArcRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string ArcMigrationRequest = "ArcMigrationRequest";
		}
		
		public const string ActionLogicalName = "msdyn_MigrateArc";
		
		public string ArcMigrationRequest
		{
			get
			{
				if (this.Parameters.Contains("ArcMigrationRequest"))
				{
					return ((string)(this.Parameters["ArcMigrationRequest"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ArcMigrationRequest"] = value;
			}
		}
		
		public msdyn_MigrateArcRequest()
		{
			this.RequestName = "msdyn_MigrateArc";
			this.ArcMigrationRequest = default(string);
		}
	}
}