//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_ExecuteSISampleDataRequest")]
	public partial class msdyn_ExecuteSISampleDataRequestRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Operation = "Operation";
			public const string Version = "Version";
			public const string Lcid = "Lcid";
		}
		
		public const string ActionLogicalName = "msdyn_ExecuteSISampleDataRequest";
		
		public string Operation
		{
			get
			{
				if (this.Parameters.Contains("Operation"))
				{
					return ((string)(this.Parameters["Operation"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Operation"] = value;
			}
		}
		
		public string Version
		{
			get
			{
				if (this.Parameters.Contains("Version"))
				{
					return ((string)(this.Parameters["Version"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Version"] = value;
			}
		}
		
		public string Lcid
		{
			get
			{
				if (this.Parameters.Contains("Lcid"))
				{
					return ((string)(this.Parameters["Lcid"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Lcid"] = value;
			}
		}
		
		public msdyn_ExecuteSISampleDataRequestRequest()
		{
			this.RequestName = "msdyn_ExecuteSISampleDataRequest";
			this.Operation = default(string);
		}
	}
}