//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_EnableSharePoint")]
	public partial class msdyn_EnableSharePointResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string OperationResult = "OperationResult";
		}
		
		public const string ActionLogicalName = "msdyn_EnableSharePoint";
		
		public msdyn_EnableSharePointResponse()
		{
		}
		
		public bool OperationResult
		{
			get
			{
				if (this.Results.Contains("OperationResult"))
				{
					return ((bool)(this.Results["OperationResult"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["OperationResult"] = value;
			}
		}
	}
}