//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetIoTVisualizationSummary")]
	public partial class msdyn_GetIoTVisualizationSummaryResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string SummaryOutput = "SummaryOutput";
		}
		
		public const string ActionLogicalName = "msdyn_GetIoTVisualizationSummary";
		
		public msdyn_GetIoTVisualizationSummaryResponse()
		{
		}
		
		public string SummaryOutput
		{
			get
			{
				if (this.Results.Contains("SummaryOutput"))
				{
					return ((string)(this.Results["SummaryOutput"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["SummaryOutput"] = value;
			}
		}
	}
}