//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetAnalyticsReportToken")]
	public partial class msdyn_GetAnalyticsReportTokenResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string Expiration = "Expiration";
			public const string Token = "Token";
		}
		
		public const string ActionLogicalName = "msdyn_GetAnalyticsReportToken";
		
		public msdyn_GetAnalyticsReportTokenResponse()
		{
		}
		
		public System.DateTime Expiration
		{
			get
			{
				if (this.Results.Contains("Expiration"))
				{
					return ((System.DateTime)(this.Results["Expiration"]));
				}
				else
				{
					return default(System.DateTime);
				}
			}
			set
			{
				this.Results["Expiration"] = value;
			}
		}
		
		public string Token
		{
			get
			{
				if (this.Results.Contains("Token"))
				{
					return ((string)(this.Results["Token"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Token"] = value;
			}
		}
	}
}