//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_IoTGetDeviceEvents")]
	public partial class msdyn_IoTGetDeviceEventsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string EventsData = "EventsData";
		}
		
		public const string ActionLogicalName = "msdyn_IoTGetDeviceEvents";
		
		public msdyn_IoTGetDeviceEventsResponse()
		{
		}
		
		public string EventsData
		{
			get
			{
				if (this.Results.Contains("EventsData"))
				{
					return ((string)(this.Results["EventsData"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["EventsData"] = value;
			}
		}
	}
}