//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_RetrieveSearchProviders")]
	public partial class msdyn_RetrieveSearchProvidersRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string ApplicationId = "ApplicationId";
		}
		
		public const string ActionLogicalName = "msdyn_RetrieveSearchProviders";
		
		public string ApplicationId
		{
			get
			{
				if (this.Parameters.Contains("ApplicationId"))
				{
					return ((string)(this.Parameters["ApplicationId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ApplicationId"] = value;
			}
		}
		
		public msdyn_RetrieveSearchProvidersRequest()
		{
			this.RequestName = "msdyn_RetrieveSearchProviders";
		}
	}
}