//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_IoTNewPrimaryAlert")]
	public partial class msdyn_IoTNewPrimaryAlertRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string PrimaryAlert = "PrimaryAlert";
		}
		
		public const string ActionLogicalName = "msdyn_IoTNewPrimaryAlert";
		
		public Microsoft.Xrm.Sdk.EntityReference PrimaryAlert
		{
			get
			{
				if (this.Parameters.Contains("PrimaryAlert"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["PrimaryAlert"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["PrimaryAlert"] = value;
			}
		}
		
		public msdyn_IoTNewPrimaryAlertRequest()
		{
			this.RequestName = "msdyn_IoTNewPrimaryAlert";
			this.PrimaryAlert = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
}