//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_InvokeServiceStoredProc")]
	public partial class msdyn_InvokeServiceStoredProcRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string ProcId = "ProcId";
			public const string BatchSize = "BatchSize";
			public const string BatchStart = "BatchStart";
		}
		
		public const string ActionLogicalName = "msdyn_InvokeServiceStoredProc";
		
		public int ProcId
		{
			get
			{
				if (this.Parameters.Contains("ProcId"))
				{
					return ((int)(this.Parameters["ProcId"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["ProcId"] = value;
			}
		}
		
		public int BatchSize
		{
			get
			{
				if (this.Parameters.Contains("BatchSize"))
				{
					return ((int)(this.Parameters["BatchSize"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["BatchSize"] = value;
			}
		}
		
		public int BatchStart
		{
			get
			{
				if (this.Parameters.Contains("BatchStart"))
				{
					return ((int)(this.Parameters["BatchStart"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["BatchStart"] = value;
			}
		}
		
		public msdyn_InvokeServiceStoredProcRequest()
		{
			this.RequestName = "msdyn_InvokeServiceStoredProc";
			this.ProcId = default(int);
			this.BatchSize = default(int);
			this.BatchStart = default(int);
		}
	}
}