//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_CreateApmEventHandler")]
	public partial class msdyn_CreateApmEventHandlerRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string AppModuleId = "AppModuleId";
		}
		
		public const string ActionLogicalName = "msdyn_CreateApmEventHandler";
		
		public string AppModuleId
		{
			get
			{
				if (this.Parameters.Contains("AppModuleId"))
				{
					return ((string)(this.Parameters["AppModuleId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["AppModuleId"] = value;
			}
		}
		
		public msdyn_CreateApmEventHandlerRequest()
		{
			this.RequestName = "msdyn_CreateApmEventHandler";
			this.AppModuleId = default(string);
		}
	}
}