//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_CheckFetchXmlAndLayoutXmlOfSavedQueries")]
	public partial class msdyn_CheckFetchXmlAndLayoutXmlOfSavedQueriesRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string IdFetchAndLayoutXmlList = "IdFetchAndLayoutXmlList";
		}
		
		public const string ActionLogicalName = "msdyn_CheckFetchXmlAndLayoutXmlOfSavedQueries";
		
		public string IdFetchAndLayoutXmlList
		{
			get
			{
				if (this.Parameters.Contains("IdFetchAndLayoutXmlList"))
				{
					return ((string)(this.Parameters["IdFetchAndLayoutXmlList"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["IdFetchAndLayoutXmlList"] = value;
			}
		}
		
		public msdyn_CheckFetchXmlAndLayoutXmlOfSavedQueriesRequest()
		{
			this.RequestName = "msdyn_CheckFetchXmlAndLayoutXmlOfSavedQueries";
			this.IdFetchAndLayoutXmlList = default(string);
		}
	}
}