//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetSIPackageStatus")]
	public partial class msdyn_GetSIPackageStatusRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string ApiVersion = "ApiVersion";
		}
		
		public const string ActionLogicalName = "msdyn_GetSIPackageStatus";
		
		public string ApiVersion
		{
			get
			{
				if (this.Parameters.Contains("ApiVersion"))
				{
					return ((string)(this.Parameters["ApiVersion"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ApiVersion"] = value;
			}
		}
		
		public msdyn_GetSIPackageStatusRequest()
		{
			this.RequestName = "msdyn_GetSIPackageStatus";
		}
	}
}