//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_CreateSimilarOpportunitiyPredictionModel")]
	public partial class msdyn_CreateSimilarOpportunitiyPredictionModelRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string ModelState = "ModelState";
		}
		
		public const string ActionLogicalName = "msdyn_CreateSimilarOpportunitiyPredictionModel";
		
		public string ModelState
		{
			get
			{
				if (this.Parameters.Contains("ModelState"))
				{
					return ((string)(this.Parameters["ModelState"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ModelState"] = value;
			}
		}
		
		public msdyn_CreateSimilarOpportunitiyPredictionModelRequest()
		{
			this.RequestName = "msdyn_CreateSimilarOpportunitiyPredictionModel";
		}
	}
}