//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetKAObjectFromTemplate")]
	public partial class msdyn_GetKAObjectFromTemplateRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string TemplateId = "TemplateId";
			public const string Target = "Target";
		}
		
		public const string ActionLogicalName = "msdyn_GetKAObjectFromTemplate";
		
		public string TemplateId
		{
			get
			{
				if (this.Parameters.Contains("TemplateId"))
				{
					return ((string)(this.Parameters["TemplateId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["TemplateId"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public msdyn_GetKAObjectFromTemplateRequest()
		{
			this.RequestName = "msdyn_GetKAObjectFromTemplate";
			this.TemplateId = default(string);
		}
	}
}