//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_SetTeamsDocumentStatus")]
	public partial class msdyn_SetTeamsDocumentStatusResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string FailedLogicalEntityNames = "FailedLogicalEntityNames";
			public const string OperationResult = "OperationResult";
			public const string PassedLogicalEntityNames = "PassedLogicalEntityNames";
		}
		
		public const string ActionLogicalName = "msdyn_SetTeamsDocumentStatus";
		
		public msdyn_SetTeamsDocumentStatusResponse()
		{
		}
		
		public string FailedLogicalEntityNames
		{
			get
			{
				if (this.Results.Contains("FailedLogicalEntityNames"))
				{
					return ((string)(this.Results["FailedLogicalEntityNames"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["FailedLogicalEntityNames"] = value;
			}
		}
		
		public bool OperationResult
		{
			get
			{
				if (this.Results.Contains("OperationResult"))
				{
					return ((bool)(this.Results["OperationResult"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["OperationResult"] = value;
			}
		}
		
		public string PassedLogicalEntityNames
		{
			get
			{
				if (this.Results.Contains("PassedLogicalEntityNames"))
				{
					return ((string)(this.Results["PassedLogicalEntityNames"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["PassedLogicalEntityNames"] = value;
			}
		}
	}
}