//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_CreateSuggestedContact")]
	public partial class msdyn_CreateSuggestedContactRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string SuggestedContactId = "SuggestedContactId";
		}
		
		public const string ActionLogicalName = "msdyn_CreateSuggestedContact";
		
		public string SuggestedContactId
		{
			get
			{
				if (this.Parameters.Contains("SuggestedContactId"))
				{
					return ((string)(this.Parameters["SuggestedContactId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SuggestedContactId"] = value;
			}
		}
		
		public msdyn_CreateSuggestedContactRequest()
		{
			this.RequestName = "msdyn_CreateSuggestedContact";
			this.SuggestedContactId = default(string);
		}
	}
}