//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_ActivateProcesses")]
	public partial class msdyn_ActivateProcessesResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string ResolutionState = "ResolutionState";
			public const string ResolvedRecordsCount = "ResolvedRecordsCount";
		}
		
		public const string ActionLogicalName = "msdyn_ActivateProcesses";
		
		public msdyn_ActivateProcessesResponse()
		{
		}
		
		public int ResolutionState
		{
			get
			{
				if (this.Results.Contains("ResolutionState"))
				{
					return ((int)(this.Results["ResolutionState"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Results["ResolutionState"] = value;
			}
		}
		
		public int ResolvedRecordsCount
		{
			get
			{
				if (this.Results.Contains("ResolvedRecordsCount"))
				{
					return ((int)(this.Results["ResolvedRecordsCount"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Results["ResolvedRecordsCount"] = value;
			}
		}
	}
}