//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetIoTAlertAggregation")]
	public partial class msdyn_GetIoTAlertAggregationRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string DeviceId = "DeviceId";
			public const string TimeRangeValue = "TimeRangeValue";
			public const string TimeRangeType = "TimeRangeType";
		}
		
		public const string ActionLogicalName = "msdyn_GetIoTAlertAggregation";
		
		public string DeviceId
		{
			get
			{
				if (this.Parameters.Contains("DeviceId"))
				{
					return ((string)(this.Parameters["DeviceId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["DeviceId"] = value;
			}
		}
		
		public int TimeRangeValue
		{
			get
			{
				if (this.Parameters.Contains("TimeRangeValue"))
				{
					return ((int)(this.Parameters["TimeRangeValue"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["TimeRangeValue"] = value;
			}
		}
		
		public string TimeRangeType
		{
			get
			{
				if (this.Parameters.Contains("TimeRangeType"))
				{
					return ((string)(this.Parameters["TimeRangeType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["TimeRangeType"] = value;
			}
		}
		
		public msdyn_GetIoTAlertAggregationRequest()
		{
			this.RequestName = "msdyn_GetIoTAlertAggregation";
			this.DeviceId = default(string);
			this.TimeRangeValue = default(int);
			this.TimeRangeType = default(string);
		}
	}
}