//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_IoTPullDeviceDataActionHandler")]
	public partial class msdyn_IoTPullDeviceDataActionHandlerResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string PullDeviceDataResultsJSON = "PullDeviceDataResultsJSON";
		}
		
		public const string ActionLogicalName = "msdyn_IoTPullDeviceDataActionHandler";
		
		public msdyn_IoTPullDeviceDataActionHandlerResponse()
		{
		}
		
		public string PullDeviceDataResultsJSON
		{
			get
			{
				if (this.Results.Contains("PullDeviceDataResultsJSON"))
				{
					return ((string)(this.Results["PullDeviceDataResultsJSON"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["PullDeviceDataResultsJSON"] = value;
			}
		}
	}
}