//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_getAppConfigByContext")]
	public partial class msdyn_getAppConfigByContextResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string AppConfigurations = "AppConfigurations";
		}
		
		public const string ActionLogicalName = "msdyn_getAppConfigByContext";
		
		public msdyn_getAppConfigByContextResponse()
		{
		}
		
		public string AppConfigurations
		{
			get
			{
				if (this.Results.Contains("AppConfigurations"))
				{
					return ((string)(this.Results["AppConfigurations"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["AppConfigurations"] = value;
			}
		}
	}
}