//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_PostRetrieveRealTimeSuggestedActivities")]
	public partial class msdyn_PostRetrieveRealTimeSuggestedActivitiesRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string entityId = "entityId";
			public const string entityName = "entityName";
		}
		
		public const string ActionLogicalName = "msdyn_PostRetrieveRealTimeSuggestedActivities";
		
		public string entityId
		{
			get
			{
				if (this.Parameters.Contains("entityId"))
				{
					return ((string)(this.Parameters["entityId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["entityId"] = value;
			}
		}
		
		public string entityName
		{
			get
			{
				if (this.Parameters.Contains("entityName"))
				{
					return ((string)(this.Parameters["entityName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["entityName"] = value;
			}
		}
		
		public msdyn_PostRetrieveRealTimeSuggestedActivitiesRequest()
		{
			this.RequestName = "msdyn_PostRetrieveRealTimeSuggestedActivities";
			this.entityId = default(string);
			this.entityName = default(string);
		}
	}
}