//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetServiceBaseUrl")]
	public partial class msdyn_GetServiceBaseUrlResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string BaseUrl = "BaseUrl";
		}
		
		public const string ActionLogicalName = "msdyn_GetServiceBaseUrl";
		
		public msdyn_GetServiceBaseUrlResponse()
		{
		}
		
		public string BaseUrl
		{
			get
			{
				if (this.Results.Contains("BaseUrl"))
				{
					return ((string)(this.Results["BaseUrl"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["BaseUrl"] = value;
			}
		}
	}
}