//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_ProvisionIoTSuggestionsMLModelInternal")]
	public partial class msdyn_ProvisionIoTSuggestionsMLModelInternalRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string TenantId = "TenantId";
		}
		
		public const string ActionLogicalName = "msdyn_ProvisionIoTSuggestionsMLModelInternal";
		
		public string TenantId
		{
			get
			{
				if (this.Parameters.Contains("TenantId"))
				{
					return ((string)(this.Parameters["TenantId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["TenantId"] = value;
			}
		}
		
		public msdyn_ProvisionIoTSuggestionsMLModelInternalRequest()
		{
			this.RequestName = "msdyn_ProvisionIoTSuggestionsMLModelInternal";
			this.TenantId = default(string);
		}
	}
}