//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_IoTHubQueryDeviceReadings")]
	public partial class msdyn_IoTHubQueryDeviceReadingsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string AggregatedDeviceReadings = "AggregatedDeviceReadings";
		}
		
		public const string ActionLogicalName = "msdyn_IoTHubQueryDeviceReadings";
		
		public msdyn_IoTHubQueryDeviceReadingsResponse()
		{
		}
		
		public string AggregatedDeviceReadings
		{
			get
			{
				if (this.Results.Contains("AggregatedDeviceReadings"))
				{
					return ((string)(this.Results["AggregatedDeviceReadings"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["AggregatedDeviceReadings"] = value;
			}
		}
	}
}