//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_MigrateSla")]
	public partial class msdyn_MigrateSlaRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string SlaMigrationRequest = "SlaMigrationRequest";
		}
		
		public const string ActionLogicalName = "msdyn_MigrateSla";
		
		public string SlaMigrationRequest
		{
			get
			{
				if (this.Parameters.Contains("SlaMigrationRequest"))
				{
					return ((string)(this.Parameters["SlaMigrationRequest"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SlaMigrationRequest"] = value;
			}
		}
		
		public msdyn_MigrateSlaRequest()
		{
			this.RequestName = "msdyn_MigrateSla";
			this.SlaMigrationRequest = default(string);
		}
	}
}