//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_IsMSTeamsUserSyncFeatureEnabled")]
	public partial class msdyn_IsMSTeamsUserSyncFeatureEnabledResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string DisabledReason = "DisabledReason";
			public const string IsEnabled = "IsEnabled";
		}
		
		public const string ActionLogicalName = "msdyn_IsMSTeamsUserSyncFeatureEnabled";
		
		public msdyn_IsMSTeamsUserSyncFeatureEnabledResponse()
		{
		}
		
		public string DisabledReason
		{
			get
			{
				if (this.Results.Contains("DisabledReason"))
				{
					return ((string)(this.Results["DisabledReason"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["DisabledReason"] = value;
			}
		}
		
		public bool IsEnabled
		{
			get
			{
				if (this.Results.Contains("IsEnabled"))
				{
					return ((bool)(this.Results["IsEnabled"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["IsEnabled"] = value;
			}
		}
	}
}