//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_PerformNotesAnalysisAction")]
	public partial class msdyn_PerformNotesAnalysisActionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string EntityName = "EntityName";
			public const string SerializedAction = "SerializedAction";
			public const string ParentEntityName = "ParentEntityName";
			public const string ParentEntityId = "ParentEntityId";
		}
		
		public const string ActionLogicalName = "msdyn_PerformNotesAnalysisAction";
		
		public string EntityName
		{
			get
			{
				if (this.Parameters.Contains("EntityName"))
				{
					return ((string)(this.Parameters["EntityName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["EntityName"] = value;
			}
		}
		
		public string SerializedAction
		{
			get
			{
				if (this.Parameters.Contains("SerializedAction"))
				{
					return ((string)(this.Parameters["SerializedAction"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SerializedAction"] = value;
			}
		}
		
		public string ParentEntityName
		{
			get
			{
				if (this.Parameters.Contains("ParentEntityName"))
				{
					return ((string)(this.Parameters["ParentEntityName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ParentEntityName"] = value;
			}
		}
		
		public string ParentEntityId
		{
			get
			{
				if (this.Parameters.Contains("ParentEntityId"))
				{
					return ((string)(this.Parameters["ParentEntityId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ParentEntityId"] = value;
			}
		}
		
		public msdyn_PerformNotesAnalysisActionRequest()
		{
			this.RequestName = "msdyn_PerformNotesAnalysisAction";
		}
	}
}