//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_RetrieveKnowledgeSuggestions")]
	public partial class msdyn_RetrieveKnowledgeSuggestionsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Count = "Count";
			public const string Target = "Target";
		}
		
		public const string ActionLogicalName = "msdyn_RetrieveKnowledgeSuggestions";
		
		public int Count
		{
			get
			{
				if (this.Parameters.Contains("Count"))
				{
					return ((int)(this.Parameters["Count"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["Count"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public msdyn_RetrieveKnowledgeSuggestionsRequest()
		{
			this.RequestName = "msdyn_RetrieveKnowledgeSuggestions";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
}