//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_ExecuteARC")]
	public partial class msdyn_ExecuteARCRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string CreatedEntityReference = "CreatedEntityReference";
			public const string RuleId = "RuleId";
		}
		
		public const string ActionLogicalName = "msdyn_ExecuteARC";
		
		public Microsoft.Xrm.Sdk.EntityReference CreatedEntityReference
		{
			get
			{
				if (this.Parameters.Contains("CreatedEntityReference"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["CreatedEntityReference"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["CreatedEntityReference"] = value;
			}
		}
		
		public string RuleId
		{
			get
			{
				if (this.Parameters.Contains("RuleId"))
				{
					return ((string)(this.Parameters["RuleId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RuleId"] = value;
			}
		}
		
		public msdyn_ExecuteARCRequest()
		{
			this.RequestName = "msdyn_ExecuteARC";
			this.CreatedEntityReference = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
}