//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetAdditionalPropertiesMetadata")]
	public partial class msdyn_GetAdditionalPropertiesMetadataResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string Metadata = "Metadata";
		}
		
		public const string ActionLogicalName = "msdyn_GetAdditionalPropertiesMetadata";
		
		public msdyn_GetAdditionalPropertiesMetadataResponse()
		{
		}
		
		public string Metadata
		{
			get
			{
				if (this.Results.Contains("Metadata"))
				{
					return ((string)(this.Results["Metadata"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Metadata"] = value;
			}
		}
	}
}