//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_UpdateUserConsentBasedonSecurityRoles")]
	public partial class msdyn_UpdateUserConsentBasedonSecurityRolesRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string SecurityRolesList = "SecurityRolesList";
		}
		
		public const string ActionLogicalName = "msdyn_UpdateUserConsentBasedonSecurityRoles";
		
		public string SecurityRolesList
		{
			get
			{
				if (this.Parameters.Contains("SecurityRolesList"))
				{
					return ((string)(this.Parameters["SecurityRolesList"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SecurityRolesList"] = value;
			}
		}
		
		public msdyn_UpdateUserConsentBasedonSecurityRolesRequest()
		{
			this.RequestName = "msdyn_UpdateUserConsentBasedonSecurityRoles";
			this.SecurityRolesList = default(string);
		}
	}
}