//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_DeleteCalendar")]
	public partial class msdyn_DeleteCalendarResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string InnerCalendarId = "InnerCalendarId";
		}
		
		public const string ActionLogicalName = "msdyn_DeleteCalendar";
		
		public msdyn_DeleteCalendarResponse()
		{
		}
		
		public string InnerCalendarId
		{
			get
			{
				if (this.Results.Contains("InnerCalendarId"))
				{
					return ((string)(this.Results["InnerCalendarId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["InnerCalendarId"] = value;
			}
		}
	}
}