//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_TrackExchangeActivity")]
	public partial class msdyn_TrackExchangeActivityResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string ExchangeResponse = "ExchangeResponse";
		}
		
		public const string ActionLogicalName = "msdyn_TrackExchangeActivity";
		
		public msdyn_TrackExchangeActivityResponse()
		{
		}
		
		public string ExchangeResponse
		{
			get
			{
				if (this.Results.Contains("ExchangeResponse"))
				{
					return ((string)(this.Results["ExchangeResponse"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["ExchangeResponse"] = value;
			}
		}
	}
}