//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetAdditionalPropertiesMetadata")]
	public partial class msdyn_GetAdditionalPropertiesMetadataRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Type = "Type";
		}
		
		public const string ActionLogicalName = "msdyn_GetAdditionalPropertiesMetadata";
		
		public int Type
		{
			get
			{
				if (this.Parameters.Contains("Type"))
				{
					return ((int)(this.Parameters["Type"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["Type"] = value;
			}
		}
		
		public msdyn_GetAdditionalPropertiesMetadataRequest()
		{
			this.RequestName = "msdyn_GetAdditionalPropertiesMetadata";
			this.Type = default(int);
		}
	}
}