//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_RetrieveKPIvaluesfromDCI")]
	public partial class msdyn_RetrieveKPIvaluesfromDCIRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string CrmRecord = "CrmRecord";
			public const string KPINameFilterMap = "KPINameFilterMap";
			public const string SimilarEntities = "SimilarEntities";
		}
		
		public const string ActionLogicalName = "msdyn_RetrieveKPIvaluesfromDCI";
		
		public Microsoft.Xrm.Sdk.EntityReference CrmRecord
		{
			get
			{
				if (this.Parameters.Contains("CrmRecord"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["CrmRecord"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["CrmRecord"] = value;
			}
		}
		
		public string KPINameFilterMap
		{
			get
			{
				if (this.Parameters.Contains("KPINameFilterMap"))
				{
					return ((string)(this.Parameters["KPINameFilterMap"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["KPINameFilterMap"] = value;
			}
		}
		
		public string SimilarEntities
		{
			get
			{
				if (this.Parameters.Contains("SimilarEntities"))
				{
					return ((string)(this.Parameters["SimilarEntities"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SimilarEntities"] = value;
			}
		}
		
		public msdyn_RetrieveKPIvaluesfromDCIRequest()
		{
			this.RequestName = "msdyn_RetrieveKPIvaluesfromDCI";
		}
	}
}