//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_UpgradeTelemetry")]
	public partial class msdyn_UpgradeTelemetryRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string EventId = "EventId";
			public const string RunId = "RunId";
			public const string PackageName = "PackageName";
			public const string SolutionName = "SolutionName";
			public const string StartingVersion = "StartingVersion";
			public const string TargetVersion = "TargetVersion";
			public const string DurationSeconds = "DurationSeconds";
			public const string Success = "Success";
			public const string StepId = "StepId";
			public const string StepName = "StepName";
			public const string ErrorMessage = "ErrorMessage";
			public const string Details = "Details";
		}
		
		public const string ActionLogicalName = "msdyn_UpgradeTelemetry";
		
		public int EventId
		{
			get
			{
				if (this.Parameters.Contains("EventId"))
				{
					return ((int)(this.Parameters["EventId"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["EventId"] = value;
			}
		}
		
		public string RunId
		{
			get
			{
				if (this.Parameters.Contains("RunId"))
				{
					return ((string)(this.Parameters["RunId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RunId"] = value;
			}
		}
		
		public string PackageName
		{
			get
			{
				if (this.Parameters.Contains("PackageName"))
				{
					return ((string)(this.Parameters["PackageName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["PackageName"] = value;
			}
		}
		
		public string SolutionName
		{
			get
			{
				if (this.Parameters.Contains("SolutionName"))
				{
					return ((string)(this.Parameters["SolutionName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SolutionName"] = value;
			}
		}
		
		public string StartingVersion
		{
			get
			{
				if (this.Parameters.Contains("StartingVersion"))
				{
					return ((string)(this.Parameters["StartingVersion"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["StartingVersion"] = value;
			}
		}
		
		public string TargetVersion
		{
			get
			{
				if (this.Parameters.Contains("TargetVersion"))
				{
					return ((string)(this.Parameters["TargetVersion"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["TargetVersion"] = value;
			}
		}
		
		public int DurationSeconds
		{
			get
			{
				if (this.Parameters.Contains("DurationSeconds"))
				{
					return ((int)(this.Parameters["DurationSeconds"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["DurationSeconds"] = value;
			}
		}
		
		public int Success
		{
			get
			{
				if (this.Parameters.Contains("Success"))
				{
					return ((int)(this.Parameters["Success"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["Success"] = value;
			}
		}
		
		public string StepId
		{
			get
			{
				if (this.Parameters.Contains("StepId"))
				{
					return ((string)(this.Parameters["StepId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["StepId"] = value;
			}
		}
		
		public string StepName
		{
			get
			{
				if (this.Parameters.Contains("StepName"))
				{
					return ((string)(this.Parameters["StepName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["StepName"] = value;
			}
		}
		
		public string ErrorMessage
		{
			get
			{
				if (this.Parameters.Contains("ErrorMessage"))
				{
					return ((string)(this.Parameters["ErrorMessage"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ErrorMessage"] = value;
			}
		}
		
		public string Details
		{
			get
			{
				if (this.Parameters.Contains("Details"))
				{
					return ((string)(this.Parameters["Details"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Details"] = value;
			}
		}
		
		public msdyn_UpgradeTelemetryRequest()
		{
			this.RequestName = "msdyn_UpgradeTelemetry";
			this.EventId = default(int);
		}
	}
}