//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetAnalyticsReportDetail")]
	public partial class msdyn_GetAnalyticsReportDetailRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string AnalyticsRecordId = "AnalyticsRecordId";
		}
		
		public const string ActionLogicalName = "msdyn_GetAnalyticsReportDetail";
		
		public string AnalyticsRecordId
		{
			get
			{
				if (this.Parameters.Contains("AnalyticsRecordId"))
				{
					return ((string)(this.Parameters["AnalyticsRecordId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["AnalyticsRecordId"] = value;
			}
		}
		
		public msdyn_GetAnalyticsReportDetailRequest()
		{
			this.RequestName = "msdyn_GetAnalyticsReportDetail";
			this.AnalyticsRecordId = default(string);
		}
	}
}