//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_IoTCheckIfRecordExistsInEntity")]
	public partial class msdyn_IoTCheckIfRecordExistsInEntityResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string IsRecordExists = "IsRecordExists";
		}
		
		public const string ActionLogicalName = "msdyn_IoTCheckIfRecordExistsInEntity";
		
		public msdyn_IoTCheckIfRecordExistsInEntityResponse()
		{
		}
		
		public bool IsRecordExists
		{
			get
			{
				if (this.Results.Contains("IsRecordExists"))
				{
					return ((bool)(this.Results["IsRecordExists"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["IsRecordExists"] = value;
			}
		}
	}
}