//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_ManageSLAInstances")]
	public partial class msdyn_ManageSLAInstancesRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string SLAId = "SLAId";
			public const string RegardingId = "RegardingId";
			public const string EntityLogicalName = "EntityLogicalName";
			public const string Target = "Target";
		}
		
		public const string ActionLogicalName = "msdyn_ManageSLAInstances";
		
		public string SLAId
		{
			get
			{
				if (this.Parameters.Contains("SLAId"))
				{
					return ((string)(this.Parameters["SLAId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SLAId"] = value;
			}
		}
		
		public string RegardingId
		{
			get
			{
				if (this.Parameters.Contains("RegardingId"))
				{
					return ((string)(this.Parameters["RegardingId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RegardingId"] = value;
			}
		}
		
		public string EntityLogicalName
		{
			get
			{
				if (this.Parameters.Contains("EntityLogicalName"))
				{
					return ((string)(this.Parameters["EntityLogicalName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["EntityLogicalName"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public msdyn_ManageSLAInstancesRequest()
		{
			this.RequestName = "msdyn_ManageSLAInstances";
			this.SLAId = default(string);
			this.RegardingId = default(string);
			this.EntityLogicalName = default(string);
		}
	}
}