//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_SendEmailFromTemplate")]
	public partial class msdyn_SendEmailFromTemplateRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string From = "From";
			public const string To = "To";
			public const string Cc = "Cc";
			public const string Bcc = "Bcc";
			public const string Regarding = "Regarding";
			public const string Template = "Template";
		}
		
		public const string ActionLogicalName = "msdyn_SendEmailFromTemplate";
		
		public Microsoft.Xrm.Sdk.EntityReference From
		{
			get
			{
				if (this.Parameters.Contains("From"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["From"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["From"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection To
		{
			get
			{
				if (this.Parameters.Contains("To"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Parameters["To"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Parameters["To"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection Cc
		{
			get
			{
				if (this.Parameters.Contains("Cc"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Parameters["Cc"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Parameters["Cc"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection Bcc
		{
			get
			{
				if (this.Parameters.Contains("Bcc"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Parameters["Bcc"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Parameters["Bcc"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Regarding
		{
			get
			{
				if (this.Parameters.Contains("Regarding"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Regarding"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Regarding"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Template
		{
			get
			{
				if (this.Parameters.Contains("Template"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Template"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Template"] = value;
			}
		}
		
		public msdyn_SendEmailFromTemplateRequest()
		{
			this.RequestName = "msdyn_SendEmailFromTemplate";
			this.From = default(Microsoft.Xrm.Sdk.EntityReference);
			this.To = default(Microsoft.Xrm.Sdk.EntityCollection);
			this.Regarding = default(Microsoft.Xrm.Sdk.EntityReference);
			this.Template = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
}