//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_CreateSuggestedActivity")]
	public partial class msdyn_CreateSuggestedActivityRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string SuggestedActivityId = "SuggestedActivityId";
			public const string RegardingObjectId = "RegardingObjectId";
			public const string RegardingObjectEntity = "RegardingObjectEntity";
			public const string IsAdminConsented = "IsAdminConsented";
		}
		
		public const string ActionLogicalName = "msdyn_CreateSuggestedActivity";
		
		public string SuggestedActivityId
		{
			get
			{
				if (this.Parameters.Contains("SuggestedActivityId"))
				{
					return ((string)(this.Parameters["SuggestedActivityId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SuggestedActivityId"] = value;
			}
		}
		
		public string RegardingObjectId
		{
			get
			{
				if (this.Parameters.Contains("RegardingObjectId"))
				{
					return ((string)(this.Parameters["RegardingObjectId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RegardingObjectId"] = value;
			}
		}
		
		public string RegardingObjectEntity
		{
			get
			{
				if (this.Parameters.Contains("RegardingObjectEntity"))
				{
					return ((string)(this.Parameters["RegardingObjectEntity"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RegardingObjectEntity"] = value;
			}
		}
		
		public bool IsAdminConsented
		{
			get
			{
				if (this.Parameters.Contains("IsAdminConsented"))
				{
					return ((bool)(this.Parameters["IsAdminConsented"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["IsAdminConsented"] = value;
			}
		}
		
		public msdyn_CreateSuggestedActivityRequest()
		{
			this.RequestName = "msdyn_CreateSuggestedActivity";
			this.SuggestedActivityId = default(string);
			this.RegardingObjectId = default(string);
			this.RegardingObjectEntity = default(string);
		}
	}
}