//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetCecCompatibilityForOmniChannel")]
	public partial class msdyn_GetCecCompatibilityForOmniChannelResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string IsResolvedLegacyCommand = "IsResolvedLegacyCommand";
		}
		
		public const string ActionLogicalName = "msdyn_GetCecCompatibilityForOmniChannel";
		
		public msdyn_GetCecCompatibilityForOmniChannelResponse()
		{
		}
		
		public bool IsResolvedLegacyCommand
		{
			get
			{
				if (this.Results.Contains("IsResolvedLegacyCommand"))
				{
					return ((bool)(this.Results["IsResolvedLegacyCommand"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["IsResolvedLegacyCommand"] = value;
			}
		}
	}
}