//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_RegisterCustomEntity")]
	public partial class msdyn_RegisterCustomEntityRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string EntityIds = "EntityIds";
			public const string EntityLogicalName = "EntityLogicalName";
			public const string DeviceIds = "DeviceIds";
			public const string Names = "Names";
			public const string AccountIds = "AccountIds";
		}
		
		public const string ActionLogicalName = "msdyn_RegisterCustomEntity";
		
		public string EntityIds
		{
			get
			{
				if (this.Parameters.Contains("EntityIds"))
				{
					return ((string)(this.Parameters["EntityIds"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["EntityIds"] = value;
			}
		}
		
		public string EntityLogicalName
		{
			get
			{
				if (this.Parameters.Contains("EntityLogicalName"))
				{
					return ((string)(this.Parameters["EntityLogicalName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["EntityLogicalName"] = value;
			}
		}
		
		public string DeviceIds
		{
			get
			{
				if (this.Parameters.Contains("DeviceIds"))
				{
					return ((string)(this.Parameters["DeviceIds"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["DeviceIds"] = value;
			}
		}
		
		public string Names
		{
			get
			{
				if (this.Parameters.Contains("Names"))
				{
					return ((string)(this.Parameters["Names"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Names"] = value;
			}
		}
		
		public string AccountIds
		{
			get
			{
				if (this.Parameters.Contains("AccountIds"))
				{
					return ((string)(this.Parameters["AccountIds"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["AccountIds"] = value;
			}
		}
		
		public msdyn_RegisterCustomEntityRequest()
		{
			this.RequestName = "msdyn_RegisterCustomEntity";
			this.EntityIds = default(string);
			this.EntityLogicalName = default(string);
		}
	}
}