//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_ForecastGenerateHierarchy")]
	public partial class msdyn_ForecastGenerateHierarchyResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string ForecastCollection = "ForecastCollection";
		}
		
		public const string ActionLogicalName = "msdyn_ForecastGenerateHierarchy";
		
		public msdyn_ForecastGenerateHierarchyResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection ForecastCollection
		{
			get
			{
				if (this.Results.Contains("ForecastCollection"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Results["ForecastCollection"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Results["ForecastCollection"] = value;
			}
		}
	}
}