//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_QueryExchange")]
	public partial class msdyn_QueryExchangeResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string ExchangeData = "ExchangeData";
		}
		
		public const string ActionLogicalName = "msdyn_QueryExchange";
		
		public msdyn_QueryExchangeResponse()
		{
		}
		
		public string ExchangeData
		{
			get
			{
				if (this.Results.Contains("ExchangeData"))
				{
					return ((string)(this.Results["ExchangeData"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["ExchangeData"] = value;
			}
		}
	}
}