//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_cesinvoke")]
	public partial class msdyn_cesinvokeResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string CESResult = "CESResult";
			public const string IsSuccess = "IsSuccess";
		}
		
		public const string ActionLogicalName = "msdyn_cesinvoke";
		
		public msdyn_cesinvokeResponse()
		{
		}
		
		public string CESResult
		{
			get
			{
				if (this.Results.Contains("CESResult"))
				{
					return ((string)(this.Results["CESResult"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["CESResult"] = value;
			}
		}
		
		public string IsSuccess
		{
			get
			{
				if (this.Results.Contains("IsSuccess"))
				{
					return ((string)(this.Results["IsSuccess"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["IsSuccess"] = value;
			}
		}
	}
}