//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_ConfigureDocumentStorage")]
	public partial class msdyn_ConfigureDocumentStorageRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string customSharePointUrl = "customSharePointUrl";
			public const string clientUrl = "clientUrl";
			public const string EntityList = "EntityList";
			public const string BusinessProcessFlowId = "BusinessProcessFlowId";
			public const string BusinessProcessFlowInstanceId = "BusinessProcessFlowInstanceId";
			public const string ActionStepId = "ActionStepId";
		}
		
		public const string ActionLogicalName = "msdyn_ConfigureDocumentStorage";
		
		public string customSharePointUrl
		{
			get
			{
				if (this.Parameters.Contains("customSharePointUrl"))
				{
					return ((string)(this.Parameters["customSharePointUrl"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["customSharePointUrl"] = value;
			}
		}
		
		public string clientUrl
		{
			get
			{
				if (this.Parameters.Contains("clientUrl"))
				{
					return ((string)(this.Parameters["clientUrl"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["clientUrl"] = value;
			}
		}
		
		public string EntityList
		{
			get
			{
				if (this.Parameters.Contains("EntityList"))
				{
					return ((string)(this.Parameters["EntityList"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["EntityList"] = value;
			}
		}
		
		public string BusinessProcessFlowId
		{
			get
			{
				if (this.Parameters.Contains("BusinessProcessFlowId"))
				{
					return ((string)(this.Parameters["BusinessProcessFlowId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["BusinessProcessFlowId"] = value;
			}
		}
		
		public string BusinessProcessFlowInstanceId
		{
			get
			{
				if (this.Parameters.Contains("BusinessProcessFlowInstanceId"))
				{
					return ((string)(this.Parameters["BusinessProcessFlowInstanceId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["BusinessProcessFlowInstanceId"] = value;
			}
		}
		
		public string ActionStepId
		{
			get
			{
				if (this.Parameters.Contains("ActionStepId"))
				{
					return ((string)(this.Parameters["ActionStepId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ActionStepId"] = value;
			}
		}
		
		public msdyn_ConfigureDocumentStorageRequest()
		{
			this.RequestName = "msdyn_ConfigureDocumentStorage";
			this.clientUrl = default(string);
			this.EntityList = default(string);
		}
	}
}