//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetIoTAlertAggregation")]
	public partial class msdyn_GetIoTAlertAggregationResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string AggregateOutput = "AggregateOutput";
			public const string DialogUniqueName = "DialogUniqueName";
			public const string EntityLogicalName = "EntityLogicalName";
		}
		
		public const string ActionLogicalName = "msdyn_GetIoTAlertAggregation";
		
		public msdyn_GetIoTAlertAggregationResponse()
		{
		}
		
		public string AggregateOutput
		{
			get
			{
				if (this.Results.Contains("AggregateOutput"))
				{
					return ((string)(this.Results["AggregateOutput"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["AggregateOutput"] = value;
			}
		}
		
		public string DialogUniqueName
		{
			get
			{
				if (this.Results.Contains("DialogUniqueName"))
				{
					return ((string)(this.Results["DialogUniqueName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["DialogUniqueName"] = value;
			}
		}
		
		public string EntityLogicalName
		{
			get
			{
				if (this.Results.Contains("EntityLogicalName"))
				{
					return ((string)(this.Results["EntityLogicalName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["EntityLogicalName"] = value;
			}
		}
	}
}