//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_RegisterSolutionHealthRule")]
	public partial class msdyn_RegisterSolutionHealthRuleRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string RuleDescription = "RuleDescription";
			public const string OwningSolutionId = "OwningSolutionId";
			public const string UniqueName = "UniqueName";
			public const string ResolutionAction = "ResolutionAction";
			public const string RuleSetId = "RuleSetId";
			public const string RuleArguments = "RuleArguments";
			public const string RuleName = "RuleName";
			public const string WorkflowReference = "WorkflowReference";
			public const string ResolutionMessage = "ResolutionMessage";
		}
		
		public const string ActionLogicalName = "msdyn_RegisterSolutionHealthRule";
		
		public string RuleDescription
		{
			get
			{
				if (this.Parameters.Contains("RuleDescription"))
				{
					return ((string)(this.Parameters["RuleDescription"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RuleDescription"] = value;
			}
		}
		
		public string OwningSolutionId
		{
			get
			{
				if (this.Parameters.Contains("OwningSolutionId"))
				{
					return ((string)(this.Parameters["OwningSolutionId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["OwningSolutionId"] = value;
			}
		}
		
		public string UniqueName
		{
			get
			{
				if (this.Parameters.Contains("UniqueName"))
				{
					return ((string)(this.Parameters["UniqueName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["UniqueName"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference ResolutionAction
		{
			get
			{
				if (this.Parameters.Contains("ResolutionAction"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["ResolutionAction"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["ResolutionAction"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference RuleSetId
		{
			get
			{
				if (this.Parameters.Contains("RuleSetId"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["RuleSetId"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["RuleSetId"] = value;
			}
		}
		
		public string RuleArguments
		{
			get
			{
				if (this.Parameters.Contains("RuleArguments"))
				{
					return ((string)(this.Parameters["RuleArguments"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RuleArguments"] = value;
			}
		}
		
		public string RuleName
		{
			get
			{
				if (this.Parameters.Contains("RuleName"))
				{
					return ((string)(this.Parameters["RuleName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RuleName"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference WorkflowReference
		{
			get
			{
				if (this.Parameters.Contains("WorkflowReference"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["WorkflowReference"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["WorkflowReference"] = value;
			}
		}
		
		public string ResolutionMessage
		{
			get
			{
				if (this.Parameters.Contains("ResolutionMessage"))
				{
					return ((string)(this.Parameters["ResolutionMessage"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ResolutionMessage"] = value;
			}
		}
		
		public msdyn_RegisterSolutionHealthRuleRequest()
		{
			this.RequestName = "msdyn_RegisterSolutionHealthRule";
			this.RuleSetId = default(Microsoft.Xrm.Sdk.EntityReference);
			this.RuleName = default(string);
			this.WorkflowReference = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
}