//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_SetTalkingPointLikedStatus")]
	public partial class msdyn_SetTalkingPointLikedStatusResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string IsSuccessfull = "IsSuccessfull";
		}
		
		public const string ActionLogicalName = "msdyn_SetTalkingPointLikedStatus";
		
		public msdyn_SetTalkingPointLikedStatusResponse()
		{
		}
		
		public bool IsSuccessfull
		{
			get
			{
				if (this.Results.Contains("IsSuccessfull"))
				{
					return ((bool)(this.Results["IsSuccessfull"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["IsSuccessfull"] = value;
			}
		}
	}
}