//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetIoTCommandMetadata")]
	public partial class msdyn_GetIoTCommandMetadataResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string CommandMetadata = "CommandMetadata";
		}
		
		public const string ActionLogicalName = "msdyn_GetIoTCommandMetadata";
		
		public msdyn_GetIoTCommandMetadataResponse()
		{
		}
		
		public string CommandMetadata
		{
			get
			{
				if (this.Results.Contains("CommandMetadata"))
				{
					return ((string)(this.Results["CommandMetadata"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["CommandMetadata"] = value;
			}
		}
	}
}