//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_EditAndSaveSuggestedContact")]
	public partial class msdyn_EditAndSaveSuggestedContactRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string SuggestedContactId = "SuggestedContactId";
			public const string FirstName = "FirstName";
			public const string LastName = "LastName";
			public const string Email = "Email";
			public const string BusinessPhone = "BusinessPhone";
			public const string Address = "Address";
			public const string MobilePhone = "MobilePhone";
			public const string AccountId = "AccountId";
		}
		
		public const string ActionLogicalName = "msdyn_EditAndSaveSuggestedContact";
		
		public string SuggestedContactId
		{
			get
			{
				if (this.Parameters.Contains("SuggestedContactId"))
				{
					return ((string)(this.Parameters["SuggestedContactId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SuggestedContactId"] = value;
			}
		}
		
		public string FirstName
		{
			get
			{
				if (this.Parameters.Contains("FirstName"))
				{
					return ((string)(this.Parameters["FirstName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["FirstName"] = value;
			}
		}
		
		public string LastName
		{
			get
			{
				if (this.Parameters.Contains("LastName"))
				{
					return ((string)(this.Parameters["LastName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["LastName"] = value;
			}
		}
		
		public string Email
		{
			get
			{
				if (this.Parameters.Contains("Email"))
				{
					return ((string)(this.Parameters["Email"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Email"] = value;
			}
		}
		
		public string BusinessPhone
		{
			get
			{
				if (this.Parameters.Contains("BusinessPhone"))
				{
					return ((string)(this.Parameters["BusinessPhone"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["BusinessPhone"] = value;
			}
		}
		
		public string Address
		{
			get
			{
				if (this.Parameters.Contains("Address"))
				{
					return ((string)(this.Parameters["Address"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Address"] = value;
			}
		}
		
		public string MobilePhone
		{
			get
			{
				if (this.Parameters.Contains("MobilePhone"))
				{
					return ((string)(this.Parameters["MobilePhone"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["MobilePhone"] = value;
			}
		}
		
		public string AccountId
		{
			get
			{
				if (this.Parameters.Contains("AccountId"))
				{
					return ((string)(this.Parameters["AccountId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["AccountId"] = value;
			}
		}
		
		public msdyn_EditAndSaveSuggestedContactRequest()
		{
			this.RequestName = "msdyn_EditAndSaveSuggestedContact";
			this.SuggestedContactId = default(string);
			this.FirstName = default(string);
			this.LastName = default(string);
			this.Email = default(string);
			this.BusinessPhone = default(string);
			this.Address = default(string);
			this.MobilePhone = default(string);
			this.AccountId = default(string);
		}
	}
}