//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_InstallSalesInsightsSolution")]
	public partial class msdyn_InstallSalesInsightsSolutionResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string SolutionInstallStatus = "SolutionInstallStatus";
		}
		
		public const string ActionLogicalName = "msdyn_InstallSalesInsightsSolution";
		
		public msdyn_InstallSalesInsightsSolutionResponse()
		{
		}
		
		public string SolutionInstallStatus
		{
			get
			{
				if (this.Results.Contains("SolutionInstallStatus"))
				{
					return ((string)(this.Results["SolutionInstallStatus"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["SolutionInstallStatus"] = value;
			}
		}
	}
}