//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_CheckReqWebResourceOnSystemForm")]
	public partial class msdyn_CheckReqWebResourceOnSystemFormRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string EntityAndWebResourceList = "EntityAndWebResourceList";
		}
		
		public const string ActionLogicalName = "msdyn_CheckReqWebResourceOnSystemForm";
		
		public string EntityAndWebResourceList
		{
			get
			{
				if (this.Parameters.Contains("EntityAndWebResourceList"))
				{
					return ((string)(this.Parameters["EntityAndWebResourceList"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["EntityAndWebResourceList"] = value;
			}
		}
		
		public msdyn_CheckReqWebResourceOnSystemFormRequest()
		{
			this.RequestName = "msdyn_CheckReqWebResourceOnSystemForm";
		}
	}
}