//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_CheckIfSDKMessageProcessingStepsAreActive")]
	public partial class msdyn_CheckIfSDKMessageProcessingStepsAreActiveResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string Message = "Message";
			public const string ResultEntities = "ResultEntities";
			public const string ReturnLevel = "ReturnLevel";
			public const string ReturnSeverity = "ReturnSeverity";
			public const string ReturnStatus = "ReturnStatus";
		}
		
		public const string ActionLogicalName = "msdyn_CheckIfSDKMessageProcessingStepsAreActive";
		
		public msdyn_CheckIfSDKMessageProcessingStepsAreActiveResponse()
		{
		}
		
		public string Message
		{
			get
			{
				if (this.Results.Contains("Message"))
				{
					return ((string)(this.Results["Message"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Message"] = value;
			}
		}
		
		public string ResultEntities
		{
			get
			{
				if (this.Results.Contains("ResultEntities"))
				{
					return ((string)(this.Results["ResultEntities"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["ResultEntities"] = value;
			}
		}
		
		public int ReturnLevel
		{
			get
			{
				if (this.Results.Contains("ReturnLevel"))
				{
					return ((int)(this.Results["ReturnLevel"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Results["ReturnLevel"] = value;
			}
		}
		
		public int ReturnSeverity
		{
			get
			{
				if (this.Results.Contains("ReturnSeverity"))
				{
					return ((int)(this.Results["ReturnSeverity"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Results["ReturnSeverity"] = value;
			}
		}
		
		public int ReturnStatus
		{
			get
			{
				if (this.Results.Contains("ReturnStatus"))
				{
					return ((int)(this.Results["ReturnStatus"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Results["ReturnStatus"] = value;
			}
		}
	}
}