//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_IoTCheckIfRecordExistsInEntity")]
	public partial class msdyn_IoTCheckIfRecordExistsInEntityRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string EntitiesLogicalNames = "EntitiesLogicalNames";
		}
		
		public const string ActionLogicalName = "msdyn_IoTCheckIfRecordExistsInEntity";
		
		public string EntitiesLogicalNames
		{
			get
			{
				if (this.Parameters.Contains("EntitiesLogicalNames"))
				{
					return ((string)(this.Parameters["EntitiesLogicalNames"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["EntitiesLogicalNames"] = value;
			}
		}
		
		public msdyn_IoTCheckIfRecordExistsInEntityRequest()
		{
			this.RequestName = "msdyn_IoTCheckIfRecordExistsInEntity";
		}
	}
}