//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_EnableLinkedInDataValidation")]
	public partial class msdyn_EnableLinkedInDataValidationRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public const string ActionLogicalName = "msdyn_EnableLinkedInDataValidation";
		
		public msdyn_EnableLinkedInDataValidationRequest()
		{
			this.RequestName = "msdyn_EnableLinkedInDataValidation";
		}
	}
}