//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_ExecuteARC")]
	public partial class msdyn_ExecuteARCResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string ErrorMessage = "ErrorMessage";
			public const string FlowName = "FlowName";
		}
		
		public const string ActionLogicalName = "msdyn_ExecuteARC";
		
		public msdyn_ExecuteARCResponse()
		{
		}
		
		public string ErrorMessage
		{
			get
			{
				if (this.Results.Contains("ErrorMessage"))
				{
					return ((string)(this.Results["ErrorMessage"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["ErrorMessage"] = value;
			}
		}
		
		public string FlowName
		{
			get
			{
				if (this.Results.Contains("FlowName"))
				{
					return ((string)(this.Results["FlowName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["FlowName"] = value;
			}
		}
	}
}