//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetAutoCaptureUri")]
	public partial class msdyn_GetAutoCaptureUriResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string uri = "uri";
		}
		
		public const string ActionLogicalName = "msdyn_GetAutoCaptureUri";
		
		public msdyn_GetAutoCaptureUriResponse()
		{
		}
		
		public string uri
		{
			get
			{
				if (this.Results.Contains("uri"))
				{
					return ((string)(this.Results["uri"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["uri"] = value;
			}
		}
	}
}