//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetNotesAnalysis")]
	public partial class msdyn_GetNotesAnalysisRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string NoteText = "NoteText";
		}
		
		public const string ActionLogicalName = "msdyn_GetNotesAnalysis";
		
		public string NoteText
		{
			get
			{
				if (this.Parameters.Contains("NoteText"))
				{
					return ((string)(this.Parameters["NoteText"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["NoteText"] = value;
			}
		}
		
		public msdyn_GetNotesAnalysisRequest()
		{
			this.RequestName = "msdyn_GetNotesAnalysis";
		}
	}
}