//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_ExecuteSIRequest")]
	public partial class msdyn_ExecuteSIRequestRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string MethodName = "MethodName";
			public const string MethodParams = "MethodParams";
			public const string HttpRequestType = "HttpRequestType";
		}
		
		public const string ActionLogicalName = "msdyn_ExecuteSIRequest";
		
		public string MethodName
		{
			get
			{
				if (this.Parameters.Contains("MethodName"))
				{
					return ((string)(this.Parameters["MethodName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["MethodName"] = value;
			}
		}
		
		public string MethodParams
		{
			get
			{
				if (this.Parameters.Contains("MethodParams"))
				{
					return ((string)(this.Parameters["MethodParams"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["MethodParams"] = value;
			}
		}
		
		public string HttpRequestType
		{
			get
			{
				if (this.Parameters.Contains("HttpRequestType"))
				{
					return ((string)(this.Parameters["HttpRequestType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["HttpRequestType"] = value;
			}
		}
		
		public msdyn_ExecuteSIRequestRequest()
		{
			this.RequestName = "msdyn_ExecuteSIRequest";
			this.MethodName = default(string);
			this.HttpRequestType = default(string);
		}
	}
}