//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_ActivateSdkMessageProcessingSteps")]
	public partial class msdyn_ActivateSdkMessageProcessingStepsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string AnalysisResult = "AnalysisResult";
		}
		
		public const string ActionLogicalName = "msdyn_ActivateSdkMessageProcessingSteps";
		
		public Microsoft.Xrm.Sdk.EntityReference AnalysisResult
		{
			get
			{
				if (this.Parameters.Contains("AnalysisResult"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["AnalysisResult"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["AnalysisResult"] = value;
			}
		}
		
		public msdyn_ActivateSdkMessageProcessingStepsRequest()
		{
			this.RequestName = "msdyn_ActivateSdkMessageProcessingSteps";
		}
	}
}