//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_SetTalkingPointLikedStatus")]
	public partial class msdyn_SetTalkingPointLikedStatusRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string MessageId = "MessageId";
			public const string InferredMessageId = "InferredMessageId";
			public const string IsLiked = "IsLiked";
		}
		
		public const string ActionLogicalName = "msdyn_SetTalkingPointLikedStatus";
		
		public string MessageId
		{
			get
			{
				if (this.Parameters.Contains("MessageId"))
				{
					return ((string)(this.Parameters["MessageId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["MessageId"] = value;
			}
		}
		
		public string InferredMessageId
		{
			get
			{
				if (this.Parameters.Contains("InferredMessageId"))
				{
					return ((string)(this.Parameters["InferredMessageId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["InferredMessageId"] = value;
			}
		}
		
		public bool IsLiked
		{
			get
			{
				if (this.Parameters.Contains("IsLiked"))
				{
					return ((bool)(this.Parameters["IsLiked"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["IsLiked"] = value;
			}
		}
		
		public msdyn_SetTalkingPointLikedStatusRequest()
		{
			this.RequestName = "msdyn_SetTalkingPointLikedStatus";
		}
	}
}