//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetAutoCaptureUri")]
	public partial class msdyn_GetAutoCaptureUriRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string uriType = "uriType";
		}
		
		public const string ActionLogicalName = "msdyn_GetAutoCaptureUri";
		
		public string uriType
		{
			get
			{
				if (this.Parameters.Contains("uriType"))
				{
					return ((string)(this.Parameters["uriType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["uriType"] = value;
			}
		}
		
		public msdyn_GetAutoCaptureUriRequest()
		{
			this.RequestName = "msdyn_GetAutoCaptureUri";
			this.uriType = default(string);
		}
	}
}