//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_QueryExchange")]
	public partial class msdyn_QueryExchangeRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string method = "method";
			public const string body = "body";
			public const string requesturl = "requesturl";
		}
		
		public const string ActionLogicalName = "msdyn_QueryExchange";
		
		public string method
		{
			get
			{
				if (this.Parameters.Contains("method"))
				{
					return ((string)(this.Parameters["method"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["method"] = value;
			}
		}
		
		public string body
		{
			get
			{
				if (this.Parameters.Contains("body"))
				{
					return ((string)(this.Parameters["body"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["body"] = value;
			}
		}
		
		public string requesturl
		{
			get
			{
				if (this.Parameters.Contains("requesturl"))
				{
					return ((string)(this.Parameters["requesturl"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["requesturl"] = value;
			}
		}
		
		public msdyn_QueryExchangeRequest()
		{
			this.RequestName = "msdyn_QueryExchange";
			this.method = default(string);
			this.body = default(string);
			this.requesturl = default(string);
		}
	}
}