//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_RegisterSolutionHealthRule")]
	public partial class msdyn_RegisterSolutionHealthRuleResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string RuleId = "RuleId";
		}
		
		public const string ActionLogicalName = "msdyn_RegisterSolutionHealthRule";
		
		public msdyn_RegisterSolutionHealthRuleResponse()
		{
		}
		
		public string RuleId
		{
			get
			{
				if (this.Results.Contains("RuleId"))
				{
					return ((string)(this.Results["RuleId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["RuleId"] = value;
			}
		}
	}
}