//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_RunSolutionCheckerRules")]
	public partial class msdyn_RunSolutionCheckerRulesRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string AnalysisComponentId = "AnalysisComponentId";
		}
		
		public const string ActionLogicalName = "msdyn_RunSolutionCheckerRules";
		
		public string AnalysisComponentId
		{
			get
			{
				if (this.Parameters.Contains("AnalysisComponentId"))
				{
					return ((string)(this.Parameters["AnalysisComponentId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["AnalysisComponentId"] = value;
			}
		}
		
		public msdyn_RunSolutionCheckerRulesRequest()
		{
			this.RequestName = "msdyn_RunSolutionCheckerRules";
		}
	}
}