//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetNotesAnalysis")]
	public partial class msdyn_GetNotesAnalysisResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string IsSuccess = "IsSuccess";
			public const string NotesAnalysisResult = "NotesAnalysisResult";
		}
		
		public const string ActionLogicalName = "msdyn_GetNotesAnalysis";
		
		public msdyn_GetNotesAnalysisResponse()
		{
		}
		
		public bool IsSuccess
		{
			get
			{
				if (this.Results.Contains("IsSuccess"))
				{
					return ((bool)(this.Results["IsSuccess"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["IsSuccess"] = value;
			}
		}
		
		public string NotesAnalysisResult
		{
			get
			{
				if (this.Results.Contains("NotesAnalysisResult"))
				{
					return ((string)(this.Results["NotesAnalysisResult"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["NotesAnalysisResult"] = value;
			}
		}
	}
}