//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_CheckReqRibbonCommandDef")]
	public partial class msdyn_CheckReqRibbonCommandDefRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string CommandAndEntityList = "CommandAndEntityList";
		}
		
		public const string ActionLogicalName = "msdyn_CheckReqRibbonCommandDef";
		
		public string CommandAndEntityList
		{
			get
			{
				if (this.Parameters.Contains("CommandAndEntityList"))
				{
					return ((string)(this.Parameters["CommandAndEntityList"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["CommandAndEntityList"] = value;
			}
		}
		
		public msdyn_CheckReqRibbonCommandDefRequest()
		{
			this.RequestName = "msdyn_CheckReqRibbonCommandDef";
		}
	}
}