//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_IoTHubQueryDeviceReadings")]
	public partial class msdyn_IoTHubQueryDeviceReadingsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string From = "From";
			public const string To = "To";
			public const string Interval = "Interval";
			public const string IotDeviceId = "IotDeviceId";
		}
		
		public const string ActionLogicalName = "msdyn_IoTHubQueryDeviceReadings";
		
		public System.DateTime From
		{
			get
			{
				if (this.Parameters.Contains("From"))
				{
					return ((System.DateTime)(this.Parameters["From"]));
				}
				else
				{
					return default(System.DateTime);
				}
			}
			set
			{
				this.Parameters["From"] = value;
			}
		}
		
		public System.DateTime To
		{
			get
			{
				if (this.Parameters.Contains("To"))
				{
					return ((System.DateTime)(this.Parameters["To"]));
				}
				else
				{
					return default(System.DateTime);
				}
			}
			set
			{
				this.Parameters["To"] = value;
			}
		}
		
		public string Interval
		{
			get
			{
				if (this.Parameters.Contains("Interval"))
				{
					return ((string)(this.Parameters["Interval"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Interval"] = value;
			}
		}
		
		public string IotDeviceId
		{
			get
			{
				if (this.Parameters.Contains("IotDeviceId"))
				{
					return ((string)(this.Parameters["IotDeviceId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["IotDeviceId"] = value;
			}
		}
		
		public msdyn_IoTHubQueryDeviceReadingsRequest()
		{
			this.RequestName = "msdyn_IoTHubQueryDeviceReadings";
			this.From = default(System.DateTime);
			this.To = default(System.DateTime);
			this.Interval = default(string);
			this.IotDeviceId = default(string);
		}
	}
}