//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_ExportAndUploadToSPAction")]
	public partial class msdyn_ExportAndUploadToSPActionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string EntityLogicalName = "EntityLogicalName";
			public const string EntityId = "EntityId";
			public const string TemplateId = "TemplateId";
			public const string SPLocationId = "SPLocationId";
			public const string BusinessProcessFlowId = "BusinessProcessFlowId";
			public const string BusinessProcessFlowInstanceId = "BusinessProcessFlowInstanceId";
			public const string ActionStepId = "ActionStepId";
		}
		
		public const string ActionLogicalName = "msdyn_ExportAndUploadToSPAction";
		
		public string EntityLogicalName
		{
			get
			{
				if (this.Parameters.Contains("EntityLogicalName"))
				{
					return ((string)(this.Parameters["EntityLogicalName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["EntityLogicalName"] = value;
			}
		}
		
		public string EntityId
		{
			get
			{
				if (this.Parameters.Contains("EntityId"))
				{
					return ((string)(this.Parameters["EntityId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["EntityId"] = value;
			}
		}
		
		public string TemplateId
		{
			get
			{
				if (this.Parameters.Contains("TemplateId"))
				{
					return ((string)(this.Parameters["TemplateId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["TemplateId"] = value;
			}
		}
		
		public string SPLocationId
		{
			get
			{
				if (this.Parameters.Contains("SPLocationId"))
				{
					return ((string)(this.Parameters["SPLocationId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SPLocationId"] = value;
			}
		}
		
		public string BusinessProcessFlowId
		{
			get
			{
				if (this.Parameters.Contains("BusinessProcessFlowId"))
				{
					return ((string)(this.Parameters["BusinessProcessFlowId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["BusinessProcessFlowId"] = value;
			}
		}
		
		public string BusinessProcessFlowInstanceId
		{
			get
			{
				if (this.Parameters.Contains("BusinessProcessFlowInstanceId"))
				{
					return ((string)(this.Parameters["BusinessProcessFlowInstanceId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["BusinessProcessFlowInstanceId"] = value;
			}
		}
		
		public string ActionStepId
		{
			get
			{
				if (this.Parameters.Contains("ActionStepId"))
				{
					return ((string)(this.Parameters["ActionStepId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ActionStepId"] = value;
			}
		}
		
		public msdyn_ExportAndUploadToSPActionRequest()
		{
			this.RequestName = "msdyn_ExportAndUploadToSPAction";
		}
	}
}