//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_PostOrganizationProvisioningStatus")]
	public partial class msdyn_PostOrganizationProvisioningStatusRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string autoCaptureSettings = "autoCaptureSettings";
			public const string autoCaptureRules = "autoCaptureRules";
			public const string orgProvisioningDetails = "orgProvisioningDetails";
		}
		
		public const string ActionLogicalName = "msdyn_PostOrganizationProvisioningStatus";
		
		public string autoCaptureSettings
		{
			get
			{
				if (this.Parameters.Contains("autoCaptureSettings"))
				{
					return ((string)(this.Parameters["autoCaptureSettings"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["autoCaptureSettings"] = value;
			}
		}
		
		public string autoCaptureRules
		{
			get
			{
				if (this.Parameters.Contains("autoCaptureRules"))
				{
					return ((string)(this.Parameters["autoCaptureRules"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["autoCaptureRules"] = value;
			}
		}
		
		public string orgProvisioningDetails
		{
			get
			{
				if (this.Parameters.Contains("orgProvisioningDetails"))
				{
					return ((string)(this.Parameters["orgProvisioningDetails"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["orgProvisioningDetails"] = value;
			}
		}
		
		public msdyn_PostOrganizationProvisioningStatusRequest()
		{
			this.RequestName = "msdyn_PostOrganizationProvisioningStatus";
			this.autoCaptureSettings = default(string);
			this.autoCaptureRules = default(string);
			this.orgProvisioningDetails = default(string);
		}
	}
}