//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_JsonGetBoolean")]
	public partial class msdyn_JsonGetBooleanRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Json = "Json";
			public const string PropertyPath = "PropertyPath";
			public const string DefaultReturnValue = "DefaultReturnValue";
		}
		
		public const string ActionLogicalName = "msdyn_JsonGetBoolean";
		
		public string Json
		{
			get
			{
				if (this.Parameters.Contains("Json"))
				{
					return ((string)(this.Parameters["Json"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Json"] = value;
			}
		}
		
		public string PropertyPath
		{
			get
			{
				if (this.Parameters.Contains("PropertyPath"))
				{
					return ((string)(this.Parameters["PropertyPath"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["PropertyPath"] = value;
			}
		}
		
		public bool DefaultReturnValue
		{
			get
			{
				if (this.Parameters.Contains("DefaultReturnValue"))
				{
					return ((bool)(this.Parameters["DefaultReturnValue"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["DefaultReturnValue"] = value;
			}
		}
		
		public msdyn_JsonGetBooleanRequest()
		{
			this.RequestName = "msdyn_JsonGetBoolean";
			this.PropertyPath = default(string);
		}
	}
}