//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_ConditionXmlConversion")]
	public partial class msdyn_ConditionXmlConversionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string InputType = "InputType";
			public const string OutputType = "OutputType";
			public const string InputString = "InputString";
			public const string EntityName = "EntityName";
		}
		
		public const string ActionLogicalName = "msdyn_ConditionXmlConversion";
		
		public string InputType
		{
			get
			{
				if (this.Parameters.Contains("InputType"))
				{
					return ((string)(this.Parameters["InputType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["InputType"] = value;
			}
		}
		
		public string OutputType
		{
			get
			{
				if (this.Parameters.Contains("OutputType"))
				{
					return ((string)(this.Parameters["OutputType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["OutputType"] = value;
			}
		}
		
		public string InputString
		{
			get
			{
				if (this.Parameters.Contains("InputString"))
				{
					return ((string)(this.Parameters["InputString"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["InputString"] = value;
			}
		}
		
		public string EntityName
		{
			get
			{
				if (this.Parameters.Contains("EntityName"))
				{
					return ((string)(this.Parameters["EntityName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["EntityName"] = value;
			}
		}
		
		public msdyn_ConditionXmlConversionRequest()
		{
			this.RequestName = "msdyn_ConditionXmlConversion";
			this.InputType = default(string);
			this.OutputType = default(string);
			this.InputString = default(string);
			this.EntityName = default(string);
		}
	}
}