//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetTimeLineRecords")]
	public partial class msdyn_GetTimeLineRecordsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string TimeLineWallRecords = "TimeLineWallRecords";
		}
		
		public const string ActionLogicalName = "msdyn_GetTimeLineRecords";
		
		public msdyn_GetTimeLineRecordsResponse()
		{
		}
		
		public string TimeLineWallRecords
		{
			get
			{
				if (this.Results.Contains("TimeLineWallRecords"))
				{
					return ((string)(this.Results["TimeLineWallRecords"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["TimeLineWallRecords"] = value;
			}
		}
	}
}