//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_CreateSimilarOpportunitiyPredictionModel")]
	public partial class msdyn_CreateSimilarOpportunitiyPredictionModelResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public const string ActionLogicalName = "msdyn_CreateSimilarOpportunitiyPredictionModel";
		
		public msdyn_CreateSimilarOpportunitiyPredictionModelResponse()
		{
		}
	}
}