//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_DismissEmailInfraActionCard")]
	public partial class msdyn_DismissEmailInfraActionCardRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string ActionCardId = "ActionCardId";
			public const string MessageId = "MessageId";
			public const string CardType = "CardType";
		}
		
		public const string ActionLogicalName = "msdyn_DismissEmailInfraActionCard";
		
		public string ActionCardId
		{
			get
			{
				if (this.Parameters.Contains("ActionCardId"))
				{
					return ((string)(this.Parameters["ActionCardId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ActionCardId"] = value;
			}
		}
		
		public string MessageId
		{
			get
			{
				if (this.Parameters.Contains("MessageId"))
				{
					return ((string)(this.Parameters["MessageId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["MessageId"] = value;
			}
		}
		
		public int CardType
		{
			get
			{
				if (this.Parameters.Contains("CardType"))
				{
					return ((int)(this.Parameters["CardType"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["CardType"] = value;
			}
		}
		
		public msdyn_DismissEmailInfraActionCardRequest()
		{
			this.RequestName = "msdyn_DismissEmailInfraActionCard";
			this.ActionCardId = default(string);
			this.MessageId = default(string);
			this.CardType = default(int);
		}
	}
}