//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_InstallSalesInsightsSolution")]
	public partial class msdyn_InstallSalesInsightsSolutionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string SolutionName = "SolutionName";
			public const string ForceInstall = "ForceInstall";
		}
		
		public const string ActionLogicalName = "msdyn_InstallSalesInsightsSolution";
		
		public string SolutionName
		{
			get
			{
				if (this.Parameters.Contains("SolutionName"))
				{
					return ((string)(this.Parameters["SolutionName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SolutionName"] = value;
			}
		}
		
		public bool ForceInstall
		{
			get
			{
				if (this.Parameters.Contains("ForceInstall"))
				{
					return ((bool)(this.Parameters["ForceInstall"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["ForceInstall"] = value;
			}
		}
		
		public msdyn_InstallSalesInsightsSolutionRequest()
		{
			this.RequestName = "msdyn_InstallSalesInsightsSolution";
			this.SolutionName = default(string);
		}
	}
}