//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_IoTHubGetAggregatedDeviceReadings")]
	public partial class msdyn_IoTHubGetAggregatedDeviceReadingsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string MeasuresOutput = "MeasuresOutput";
		}
		
		public const string ActionLogicalName = "msdyn_IoTHubGetAggregatedDeviceReadings";
		
		public msdyn_IoTHubGetAggregatedDeviceReadingsResponse()
		{
		}
		
		public string MeasuresOutput
		{
			get
			{
				if (this.Results.Contains("MeasuresOutput"))
				{
					return ((string)(this.Results["MeasuresOutput"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["MeasuresOutput"] = value;
			}
		}
	}
}