//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_FindEntityForPolymorphicLookup")]
	public partial class msdyn_FindEntityForPolymorphicLookupResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string ListOfEntityValuesOnPolyLookup = "ListOfEntityValuesOnPolyLookup";
		}
		
		public const string ActionLogicalName = "msdyn_FindEntityForPolymorphicLookup";
		
		public msdyn_FindEntityForPolymorphicLookupResponse()
		{
		}
		
		public string ListOfEntityValuesOnPolyLookup
		{
			get
			{
				if (this.Results.Contains("ListOfEntityValuesOnPolyLookup"))
				{
					return ((string)(this.Results["ListOfEntityValuesOnPolyLookup"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["ListOfEntityValuesOnPolyLookup"] = value;
			}
		}
	}
}