//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_ApproveMailBox")]
	public partial class msdyn_ApproveMailBoxRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string BusinessProcessFlowId = "BusinessProcessFlowId";
			public const string BusinessProcessFlowInstanceId = "BusinessProcessFlowInstanceId";
			public const string ActionStepId = "ActionStepId";
		}
		
		public const string ActionLogicalName = "msdyn_ApproveMailBox";
		
		public string BusinessProcessFlowId
		{
			get
			{
				if (this.Parameters.Contains("BusinessProcessFlowId"))
				{
					return ((string)(this.Parameters["BusinessProcessFlowId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["BusinessProcessFlowId"] = value;
			}
		}
		
		public string BusinessProcessFlowInstanceId
		{
			get
			{
				if (this.Parameters.Contains("BusinessProcessFlowInstanceId"))
				{
					return ((string)(this.Parameters["BusinessProcessFlowInstanceId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["BusinessProcessFlowInstanceId"] = value;
			}
		}
		
		public string ActionStepId
		{
			get
			{
				if (this.Parameters.Contains("ActionStepId"))
				{
					return ((string)(this.Parameters["ActionStepId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ActionStepId"] = value;
			}
		}
		
		public msdyn_ApproveMailBoxRequest()
		{
			this.RequestName = "msdyn_ApproveMailBox";
		}
	}
}