//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_RetrieveKpiValuesFromRI")]
	public partial class msdyn_RetrieveKpiValuesFromRIRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string CrmRecord = "CrmRecord";
			public const string KpiType = "KpiType";
		}
		
		public const string ActionLogicalName = "msdyn_RetrieveKpiValuesFromRI";
		
		public Microsoft.Xrm.Sdk.EntityReference CrmRecord
		{
			get
			{
				if (this.Parameters.Contains("CrmRecord"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["CrmRecord"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["CrmRecord"] = value;
			}
		}
		
		public string KpiType
		{
			get
			{
				if (this.Parameters.Contains("KpiType"))
				{
					return ((string)(this.Parameters["KpiType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["KpiType"] = value;
			}
		}
		
		public msdyn_RetrieveKpiValuesFromRIRequest()
		{
			this.RequestName = "msdyn_RetrieveKpiValuesFromRI";
			this.CrmRecord = default(Microsoft.Xrm.Sdk.EntityReference);
			this.KpiType = default(string);
		}
	}
}