//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetHierarchyData")]
	public partial class msdyn_GetHierarchyDataRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string input = "input";
		}
		
		public const string ActionLogicalName = "msdyn_GetHierarchyData";
		
		public string input
		{
			get
			{
				if (this.Parameters.Contains("input"))
				{
					return ((string)(this.Parameters["input"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["input"] = value;
			}
		}
		
		public msdyn_GetHierarchyDataRequest()
		{
			this.RequestName = "msdyn_GetHierarchyData";
			this.input = default(string);
		}
	}
}