//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_UpgradeTelemetry")]
	public partial class msdyn_UpgradeTelemetryResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string output = "output";
		}
		
		public const string ActionLogicalName = "msdyn_UpgradeTelemetry";
		
		public msdyn_UpgradeTelemetryResponse()
		{
		}
		
		public string output
		{
			get
			{
				if (this.Results.Contains("output"))
				{
					return ((string)(this.Results["output"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["output"] = value;
			}
		}
	}
}