//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_SetSharePointDocumentStatus")]
	public partial class msdyn_SetSharePointDocumentStatusRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Enable = "Enable";
			public const string LogicalEntityNames = "LogicalEntityNames";
		}
		
		public const string ActionLogicalName = "msdyn_SetSharePointDocumentStatus";
		
		public bool Enable
		{
			get
			{
				if (this.Parameters.Contains("Enable"))
				{
					return ((bool)(this.Parameters["Enable"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["Enable"] = value;
			}
		}
		
		public string LogicalEntityNames
		{
			get
			{
				if (this.Parameters.Contains("LogicalEntityNames"))
				{
					return ((string)(this.Parameters["LogicalEntityNames"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["LogicalEntityNames"] = value;
			}
		}
		
		public msdyn_SetSharePointDocumentStatusRequest()
		{
			this.RequestName = "msdyn_SetSharePointDocumentStatus";
			this.Enable = default(bool);
			this.LogicalEntityNames = default(string);
		}
	}
}