//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_IoTGetModelStatusInternal")]
	public partial class msdyn_IoTGetModelStatusInternalRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string ScenarioId = "ScenarioId";
		}
		
		public const string ActionLogicalName = "msdyn_IoTGetModelStatusInternal";
		
		public string ScenarioId
		{
			get
			{
				if (this.Parameters.Contains("ScenarioId"))
				{
					return ((string)(this.Parameters["ScenarioId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ScenarioId"] = value;
			}
		}
		
		public msdyn_IoTGetModelStatusInternalRequest()
		{
			this.RequestName = "msdyn_IoTGetModelStatusInternal";
			this.ScenarioId = default(string);
		}
	}
}