//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_FindEntityForPolymorphicLookup")]
	public partial class msdyn_FindEntityForPolymorphicLookupRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string EntityLogicalName = "EntityLogicalName";
			public const string RecordId = "RecordId";
			public const string ListOfPolymorphicLookupsFromJSON = "ListOfPolymorphicLookupsFromJSON";
		}
		
		public const string ActionLogicalName = "msdyn_FindEntityForPolymorphicLookup";
		
		public string EntityLogicalName
		{
			get
			{
				if (this.Parameters.Contains("EntityLogicalName"))
				{
					return ((string)(this.Parameters["EntityLogicalName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["EntityLogicalName"] = value;
			}
		}
		
		public string RecordId
		{
			get
			{
				if (this.Parameters.Contains("RecordId"))
				{
					return ((string)(this.Parameters["RecordId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RecordId"] = value;
			}
		}
		
		public string ListOfPolymorphicLookupsFromJSON
		{
			get
			{
				if (this.Parameters.Contains("ListOfPolymorphicLookupsFromJSON"))
				{
					return ((string)(this.Parameters["ListOfPolymorphicLookupsFromJSON"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ListOfPolymorphicLookupsFromJSON"] = value;
			}
		}
		
		public msdyn_FindEntityForPolymorphicLookupRequest()
		{
			this.RequestName = "msdyn_FindEntityForPolymorphicLookup";
			this.EntityLogicalName = default(string);
			this.RecordId = default(string);
			this.ListOfPolymorphicLookupsFromJSON = default(string);
		}
	}
}