//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetIoTCommandMetadata")]
	public partial class msdyn_GetIoTCommandMetadataRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string IoTCommandDefinition = "IoTCommandDefinition";
		}
		
		public const string ActionLogicalName = "msdyn_GetIoTCommandMetadata";
		
		public Microsoft.Xrm.Sdk.EntityReference IoTCommandDefinition
		{
			get
			{
				if (this.Parameters.Contains("IoTCommandDefinition"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["IoTCommandDefinition"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["IoTCommandDefinition"] = value;
			}
		}
		
		public msdyn_GetIoTCommandMetadataRequest()
		{
			this.RequestName = "msdyn_GetIoTCommandMetadata";
			this.IoTCommandDefinition = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
}