//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("PowerAutomateProxy")]
	public partial class PowerAutomateProxyResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string BatchResponseContent = "BatchResponseContent";
		}
		
		public const string ActionLogicalName = "PowerAutomateProxy";
		
		public PowerAutomateProxyResponse()
		{
		}
		
		public string BatchResponseContent
		{
			get
			{
				if (this.Results.Contains("BatchResponseContent"))
				{
					return ((string)(this.Results["BatchResponseContent"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["BatchResponseContent"] = value;
			}
		}
	}
}