//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("PowerAutomateProxy")]
	public partial class PowerAutomateProxyRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string BatchRequestContent = "BatchRequestContent";
		}
		
		public const string ActionLogicalName = "PowerAutomateProxy";
		
		public string BatchRequestContent
		{
			get
			{
				if (this.Parameters.Contains("BatchRequestContent"))
				{
					return ((string)(this.Parameters["BatchRequestContent"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["BatchRequestContent"] = value;
			}
		}
		
		public PowerAutomateProxyRequest()
		{
			this.RequestName = "PowerAutomateProxy";
			this.BatchRequestContent = default(string);
		}
	}
}