//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ss.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("Predict")]
	public partial class PredictResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string response = "response";
			public const string responsev2 = "responsev2";
		}
		
		public const string ActionLogicalName = "Predict";
		
		public PredictResponse()
		{
		}
		
		public string response
		{
			get
			{
				if (this.Results.Contains("response"))
				{
					return ((string)(this.Results["response"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["response"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.Entity responsev2
		{
			get
			{
				if (this.Results.Contains("responsev2"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Results["responsev2"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
			set
			{
				this.Results["responsev2"] = value;
			}
		}
	}
}