//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("PredictionSchema")]
	public partial class PredictionSchemaRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string version = "version";
			public const string predictionMode = "predictionMode";
			public const string Target = "Target";
		}
		
		public const string ActionLogicalName = "PredictionSchema";
		
		public string version
		{
			get
			{
				if (this.Parameters.Contains("version"))
				{
					return ((string)(this.Parameters["version"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["version"] = value;
			}
		}
		
		public string predictionMode
		{
			get
			{
				if (this.Parameters.Contains("predictionMode"))
				{
					return ((string)(this.Parameters["predictionMode"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["predictionMode"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public PredictionSchemaRequest()
		{
			this.RequestName = "PredictionSchema";
			this.version = default(string);
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
}