//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("PvaAuthorize")]
	public partial class PvaAuthorizeRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Users = "Users";
			public const string SharingRoleType = "SharingRoleType";
			public const string ShareOrUnshare = "ShareOrUnshare";
			public const string Target = "Target";
		}
		
		public const string ActionLogicalName = "PvaAuthorize";
		
		public Microsoft.Xrm.Sdk.EntityCollection Users
		{
			get
			{
				if (this.Parameters.Contains("Users"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Parameters["Users"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Parameters["Users"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.OptionSetValue SharingRoleType
		{
			get
			{
				if (this.Parameters.Contains("SharingRoleType"))
				{
					return ((Microsoft.Xrm.Sdk.OptionSetValue)(this.Parameters["SharingRoleType"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.OptionSetValue);
				}
			}
			set
			{
				this.Parameters["SharingRoleType"] = value;
			}
		}
		
		public bool ShareOrUnshare
		{
			get
			{
				if (this.Parameters.Contains("ShareOrUnshare"))
				{
					return ((bool)(this.Parameters["ShareOrUnshare"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["ShareOrUnshare"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public PvaAuthorizeRequest()
		{
			this.RequestName = "PvaAuthorize";
			this.Users = default(Microsoft.Xrm.Sdk.EntityCollection);
			this.SharingRoleType = default(Microsoft.Xrm.Sdk.OptionSetValue);
			this.ShareOrUnshare = default(bool);
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
}