//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("PvaCreateBotComponents")]
	public partial class PvaCreateBotComponentsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string BotComponents = "BotComponents";
			public const string Target = "Target";
		}
		
		public const string ActionLogicalName = "PvaCreateBotComponents";
		
		public Microsoft.Xrm.Sdk.EntityCollection BotComponents
		{
			get
			{
				if (this.Parameters.Contains("BotComponents"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Parameters["BotComponents"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Parameters["BotComponents"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public PvaCreateBotComponentsRequest()
		{
			this.RequestName = "PvaCreateBotComponents";
			this.BotComponents = default(Microsoft.Xrm.Sdk.EntityCollection);
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
}