//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("PvaCreateContentSnapshot")]
	public partial class PvaCreateContentSnapshotResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string SnapshotId = "SnapshotId";
		}
		
		public const string ActionLogicalName = "PvaCreateContentSnapshot";
		
		public PvaCreateContentSnapshotResponse()
		{
		}
		
		public string SnapshotId
		{
			get
			{
				if (this.Results.Contains("SnapshotId"))
				{
					return ((string)(this.Results["SnapshotId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["SnapshotId"] = value;
			}
		}
	}
}