//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("PvaGetDirectLineEndpoint")]
	public partial class PvaGetDirectLineEndpointResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string Endpoint = "Endpoint";
		}
		
		public const string ActionLogicalName = "PvaGetDirectLineEndpoint";
		
		public PvaGetDirectLineEndpointResponse()
		{
		}
		
		public string Endpoint
		{
			get
			{
				if (this.Results.Contains("Endpoint"))
				{
					return ((string)(this.Results["Endpoint"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Endpoint"] = value;
			}
		}
	}
}