//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("PvaGetUserBots")]
	public partial class PvaGetUserBotsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string RoleType = "RoleType";
		}
		
		public const string ActionLogicalName = "PvaGetUserBots";
		
		public int RoleType
		{
			get
			{
				if (this.Parameters.Contains("RoleType"))
				{
					return ((int)(this.Parameters["RoleType"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["RoleType"] = value;
			}
		}
		
		public PvaGetUserBotsRequest()
		{
			this.RequestName = "PvaGetUserBots";
			this.RoleType = default(int);
		}
	}
}