//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("PvaGetUserBots")]
	public partial class PvaGetUserBotsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string Bots = "Bots";
		}
		
		public const string ActionLogicalName = "PvaGetUserBots";
		
		public PvaGetUserBotsResponse()
		{
		}
		
		public string Bots
		{
			get
			{
				if (this.Results.Contains("Bots"))
				{
					return ((string)(this.Results["Bots"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Bots"] = value;
			}
		}
	}
}