//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("PvaPublish")]
	public partial class PvaPublishResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string PublishedBotContentId = "PublishedBotContentId";
		}
		
		public const string ActionLogicalName = "PvaPublish";
		
		public PvaPublishResponse()
		{
		}
		
		public string PublishedBotContentId
		{
			get
			{
				if (this.Results.Contains("PublishedBotContentId"))
				{
					return ((string)(this.Results["PublishedBotContentId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["PublishedBotContentId"] = value;
			}
		}
	}
}