//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("RecognizeText")]
	public partial class RecognizeTextRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string modelId = "modelId";
			public const string base64encoded = "base64encoded";
		}
		
		public const string ActionLogicalName = "RecognizeText";
		
		public string modelId
		{
			get
			{
				if (this.Parameters.Contains("modelId"))
				{
					return ((string)(this.Parameters["modelId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["modelId"] = value;
			}
		}
		
		public string base64encoded
		{
			get
			{
				if (this.Parameters.Contains("base64encoded"))
				{
					return ((string)(this.Parameters["base64encoded"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["base64encoded"] = value;
			}
		}
		
		public RecognizeTextRequest()
		{
			this.RequestName = "RecognizeText";
			this.base64encoded = default(string);
		}
	}
}