//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("RecognizeText")]
	public partial class RecognizeTextResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string countOfPages = "countOfPages";
			public const string pages = "pages";
		}
		
		public const string ActionLogicalName = "RecognizeText";
		
		public RecognizeTextResponse()
		{
		}
		
		public decimal countOfPages
		{
			get
			{
				if (this.Results.Contains("countOfPages"))
				{
					return ((decimal)(this.Results["countOfPages"]));
				}
				else
				{
					return default(decimal);
				}
			}
			set
			{
				this.Results["countOfPages"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection pages
		{
			get
			{
				if (this.Results.Contains("pages"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Results["pages"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Results["pages"] = value;
			}
		}
	}
}