//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("RetrieveEnvironmentVariables")]
	public partial class RetrieveEnvironmentVariablesResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string EntityCollection = "EntityCollection";
		}
		
		public const string ActionLogicalName = "RetrieveEnvironmentVariables";
		
		public RetrieveEnvironmentVariablesResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection EntityCollection
		{
			get
			{
				if (this.Results.Contains("EntityCollection"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Results["EntityCollection"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Results["EntityCollection"] = value;
			}
		}
	}
}