//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("RetrieveEnvironmentVariables")]
	public partial class RetrieveEnvironmentVariablesRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string SchemaNames = "SchemaNames";
		}
		
		public const string ActionLogicalName = "RetrieveEnvironmentVariables";
		
		public string[] SchemaNames
		{
			get
			{
				if (this.Parameters.Contains("SchemaNames"))
				{
					return ((string[])(this.Parameters["SchemaNames"]));
				}
				else
				{
					return default(string[]);
				}
			}
			set
			{
				this.Parameters["SchemaNames"] = value;
			}
		}
		
		public RetrieveEnvironmentVariablesRequest()
		{
			this.RequestName = "RetrieveEnvironmentVariables";
		}
	}
}