//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("RetrieveEnvironmentVariableValue")]
	public partial class RetrieveEnvironmentVariableValueResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string Value = "Value";
		}
		
		public const string ActionLogicalName = "RetrieveEnvironmentVariableValue";
		
		public RetrieveEnvironmentVariableValueResponse()
		{
		}
		
		public string Value
		{
			get
			{
				if (this.Results.Contains("Value"))
				{
					return ((string)(this.Results["Value"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Value"] = value;
			}
		}
	}
}