//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("RetrieveCascadeDeleteAsyncJobId")]
	public partial class RetrieveCascadeDeleteAsyncJobIdResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string AsyncJobId = "AsyncJobId";
			public const string AsyncJobName = "AsyncJobName";
		}
		
		public const string ActionLogicalName = "RetrieveCascadeDeleteAsyncJobId";
		
		public RetrieveCascadeDeleteAsyncJobIdResponse()
		{
		}
		
		public System.Guid AsyncJobId
		{
			get
			{
				if (this.Results.Contains("AsyncJobId"))
				{
					return ((System.Guid)(this.Results["AsyncJobId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Results["AsyncJobId"] = value;
			}
		}
		
		public string AsyncJobName
		{
			get
			{
				if (this.Results.Contains("AsyncJobName"))
				{
					return ((string)(this.Results["AsyncJobName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["AsyncJobName"] = value;
			}
		}
	}
}