//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("RetrieveUserSetOfPrivilegesByIds")]
	public partial class RetrieveUserSetOfPrivilegesByIdsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string PrivilegeIds = "PrivilegeIds";
			public const string UserId = "UserId";
		}
		
		public const string ActionLogicalName = "RetrieveUserSetOfPrivilegesByIds";
		
		public System.Guid[] PrivilegeIds
		{
			get
			{
				if (this.Parameters.Contains("PrivilegeIds"))
				{
					return ((System.Guid[])(this.Parameters["PrivilegeIds"]));
				}
				else
				{
					return default(System.Guid[]);
				}
			}
			set
			{
				this.Parameters["PrivilegeIds"] = value;
			}
		}
		
		public System.Guid UserId
		{
			get
			{
				if (this.Parameters.Contains("UserId"))
				{
					return ((System.Guid)(this.Parameters["UserId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["UserId"] = value;
			}
		}
		
		public RetrieveUserSetOfPrivilegesByIdsRequest()
		{
			this.RequestName = "RetrieveUserSetOfPrivilegesByIds";
			this.PrivilegeIds = default(System.Guid[]);
			this.UserId = default(System.Guid);
		}
	}
}