//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebecs.PGC.CEEntityModel
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("ValidateAIConfiguration")]
	public partial class ValidateAIConfigurationRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string version = "version";
			public const string aiconfigurationId = "aiconfigurationId";
		}
		
		public const string ActionLogicalName = "ValidateAIConfiguration";
		
		public string version
		{
			get
			{
				if (this.Parameters.Contains("version"))
				{
					return ((string)(this.Parameters["version"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["version"] = value;
			}
		}
		
		public string aiconfigurationId
		{
			get
			{
				if (this.Parameters.Contains("aiconfigurationId"))
				{
					return ((string)(this.Parameters["aiconfigurationId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["aiconfigurationId"] = value;
			}
		}
		
		public ValidateAIConfigurationRequest()
		{
			this.RequestName = "ValidateAIConfiguration";
			this.version = default(string);
			this.aiconfigurationId = default(string);
		}
	}
}